-retentionPeriod=90d
-storageDataPath=/victoria-metrics-data
-httpListenAddr=:8428
-memory.allowedPercent=60
-search.maxQueryDuration=30s
-search.maxUniqueTimeseries=1000000
-promscrape.suppressDuplicateScrapeTargetErrors
