# SPDX-License-Identifier: MIT
# Grafana datasource provisioning for the Dark Mirror
# Auto-configures Prometheus and Loki as data sources on Grafana startup.

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: '15s'
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: loki
    version: 1

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex: 'service=(\w+)'
          name: Service
          url: ''
    version: 1
