// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2024-2026 Stevie Bellis. All rights reserved.

package iac

import "fmt"

// TerraformRenderer produces HCL modules and provider configurations.
type TerraformRenderer struct{}

func (r *TerraformRenderer) Backend() Backend { return BackendTerraform }

func (r *TerraformRenderer) Render(config ServiceConfig) (*RenderOutput, error) {
	if err := config.Validate(); err != nil {
		return nil, err
	}

	out := &RenderOutput{
		Backend: BackendTerraform,
		Files:   make(map[string]string),
	}

	out.Files[fmt.Sprintf("modules/%s/main.tf", config.Name)] = r.renderMain(config)
	out.Files[fmt.Sprintf("modules/%s/variables.tf", config.Name)] = r.renderVariables(config)
	out.Files[fmt.Sprintf("modules/%s/outputs.tf", config.Name)] = r.renderOutputs(config)

	return out, nil
}

func (r *TerraformRenderer) RenderAll(configs []ServiceConfig) (*RenderOutput, error) {
	out := &RenderOutput{
		Backend: BackendTerraform,
		Files:   make(map[string]string),
	}

	for _, cfg := range configs {
		single, err := r.Render(cfg)
		if err != nil {
			return nil, fmt.Errorf("render %s: %w", cfg.Name, err)
		}
		for k, v := range single.Files {
			out.Files[k] = v
		}
	}

	out.Files["main.tf"] = r.renderRoot(configs)
	out.Files["versions.tf"] = r.renderVersions()

	return out, nil
}

func (r *TerraformRenderer) Validate(config ServiceConfig) error {
	if err := config.Validate(); err != nil {
		return err
	}
	out, err := r.Render(config)
	if err != nil {
		return fmt.Errorf("validate render: %w", err)
	}
	return ValidateRenderedOutput(out, config)
}

func (r *TerraformRenderer) Diff(current, desired ServiceConfig) (string, error) {
	if err := current.Validate(); err != nil {
		return "", fmt.Errorf("current config invalid: %w", err)
	}
	if err := desired.Validate(); err != nil {
		return "", fmt.Errorf("desired config invalid: %w", err)
	}
	return DiffConfigs(current, desired), nil
}

func (r *TerraformRenderer) renderMain(config ServiceConfig) string {
	s := fmt.Sprintf(`# Terraform module for %s service

resource "docker_container" "%s" {
  name  = "%s"
  image = var.image

  ports {
    internal = var.port
    external = var.port
  }
`, config.Name, config.Name, config.Name)

	if config.GRPCPort > 0 {
		s += fmt.Sprintf(`
  ports {
    internal = var.grpc_port
    external = var.grpc_port
  }
`)
	}

	s += `
  env = [
`
	for k, v := range config.Environment {
		s += fmt.Sprintf("    \"%s=%s\",\n", k, v)
	}
	s += "  ]\n"

	// Health check
	s += fmt.Sprintf(`
  healthcheck {
    test     = ["CMD", "curl", "-f", "http://localhost:%d%s"]
    interval = "10s"
    timeout  = "5s"
    retries  = 3
  }
`, config.Port, config.HealthPath)

	// Security options
	if config.Hardening.ReadOnlyFS {
		s += "  read_only = true\n"
	}
	if config.Hardening.RunAsUser > 0 {
		s += fmt.Sprintf("  user = \"%d:%d\"\n", config.Hardening.RunAsUser, config.Hardening.RunAsGroup)
	}

	s += "}\n"
	return s
}

func (r *TerraformRenderer) renderVariables(config ServiceConfig) string {
	s := fmt.Sprintf(`# Variables for %s module

variable "port" {
  description = "HTTP listen port"
  type        = number
  default     = %d
}
`, config.Name, config.Port)

	if config.GRPCPort > 0 {
		s += fmt.Sprintf(`
variable "grpc_port" {
  description = "gRPC listen port"
  type        = number
  default     = %d
}
`, config.GRPCPort)
	}

	image := config.Image
	if image == "" {
		image = fmt.Sprintf("unheaded/%s:latest", config.Name)
	}
	s += fmt.Sprintf(`
variable "image" {
  description = "Container image"
  type        = string
  default     = "%s"
}
`, image)

	return s
}

func (r *TerraformRenderer) renderOutputs(config ServiceConfig) string {
	return fmt.Sprintf(`# Outputs for %s module

output "container_id" {
  description = "Container ID"
  value       = docker_container.%s.id
}

output "port" {
  description = "HTTP port"
  value       = var.port
}
`, config.Name, config.Name)
}

func (r *TerraformRenderer) renderRoot(configs []ServiceConfig) string {
	s := "# Unheaded infrastructure — generated by pkg/iac\n\n"
	for _, cfg := range configs {
		s += fmt.Sprintf(`module "%s" {
  source = "./modules/%s"
  port   = %d
`, cfg.Name, cfg.Name, cfg.Port)
		if cfg.GRPCPort > 0 {
			s += fmt.Sprintf("  grpc_port = %d\n", cfg.GRPCPort)
		}
		s += "}\n\n"
	}
	return s
}

func (r *TerraformRenderer) renderVersions() string {
	return `terraform {
  required_version = ">= 1.5"

  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
  }
}
`
}
