#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2024-2026 Stevie Bellis.
"""Regenerate compliance/catalog/frameworks/*.yaml (the numeric prefix is the
display order) from the publishers' own
machine-readable releases, so every framework's requirement list (the
denominator of every coverage figure, ADR-097) is the publisher's, not typed
from memory.

  NIST SP 800-53 Rev 5, CSF 2.0, SP 800-171 r3, SP 800-218 (SSDF):
      OSCAL catalogs, github.com/usnistgov/oscal-content
  FedRAMP Rev 5 Low / Moderate / High:
      FedRAMP's own baseline workbook, github.com/FedRAMP/docs-legacy
      (FedRAMP labels it LEGACY: the program moved to FedRAMP 20x; Rev 5
      baselines remain what a Rev 5 authorization is assessed against)

Each output records its source URL, retrieval time and sha256, and the
upstream version. Withdrawn controls are excluded. Every FedRAMP control is
checked to exist in the 800-53 catalog; the script fails otherwise.

Stdlib only. Usage: scripts/compliance/import-frameworks.py [--out DIR]
"""
import argparse
import datetime
import hashlib
import io
import json
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
import zipfile

OSCAL = "https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov"
CSF_REFS_XLSX = "https://csrc.nist.gov/extensions/nudp/services/json/csf/download?olirids=all"
FEDRAMP_XLSX = ("https://raw.githubusercontent.com/FedRAMP/docs-legacy/main/overrides/assets/"
                "LEGACY%20FedRAMP_Security_Controls_Baseline.xlsx")
MAX_BYTES = 64 << 20


def fetch(url):
    # Only the fixed https URLs defined above are ever fetched. NIST's CPRT
    # answers 403 to urllib's default User-Agent, so identify ourselves.
    req = urllib.request.Request(url, headers={"User-Agent": "unheaded-compliance-import (+https://github.com/unheaded/unheaded)"})
    with urllib.request.urlopen(req, timeout=120) as r:
        data = r.read(MAX_BYTES + 1)
    if len(data) > MAX_BYTES:
        sys.exit(f"{url}: larger than {MAX_BYTES} bytes")
    return data


def props(c):
    return {p["name"]: p.get("value") for p in c.get("props", [])}


def label(c):
    for p in c.get("props", []):
        if p["name"] == "label" and p.get("class") != "zero-padded":
            return p["value"]
    return c["id"]


def paren_id(lbl):
    """'Organizational Context (GV.OC)' -> 'GV.OC'; plain labels unchanged."""
    m = re.search(r"\(([^()]+)\)\s*$", lbl)
    return m.group(1) if m else lbl


def oscal_levels(cat):
    """Controls by nesting depth (0 = directly under a top-level group)."""
    levels = {}

    def walk(cs, depth, parent_title):
        for c in cs:
            if props(c).get("status") != "withdrawn":
                levels.setdefault(depth, []).append((c, parent_title))
            walk(c.get("controls", []), depth + 1, c.get("title", ""))

    for g in cat.get("groups", []):
        walk(g.get("controls", []), 0, g.get("title", ""))
    return levels


def q(s):
    return json.dumps(s, ensure_ascii=False)  # JSON strings are valid YAML scalars


def write(path, fw, requirements, provenance):
    lines = ["# GENERATED by scripts/compliance/import-frameworks.py - do not edit by hand."]
    for k, v in provenance.items():
        lines.append(f"# {k}: {v}")
    lines += ["frameworks:",
              f"  - id: {fw['id']}",
              f"    name: {q(fw['name'])}",
              f"    version: {q(fw['version'])}",
              f"    granularity: {q(fw['granularity'])}",
              f"    source: {q(fw['source'])}"]
    if fw.get("derived_from"):
        lines.append(f"    derived_from: {fw['derived_from']}")
    lines.append("    requirements:")
    for rid, title in requirements:
        lines.append(f"      - {{id: {q(rid)}, title: {q(title)}}}")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{path}: {len(requirements)} requirements")


def xlsx_sheets(data):
    m_ns = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
    r_ns = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
    ns = {"m": m_ns, "r": r_ns}
    z = zipfile.ZipFile(io.BytesIO(data))
    strings = []
    if "xl/sharedStrings.xml" in z.namelist():
        for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall("m:si", ns):
            strings.append("".join(t.text or "" for t in si.iter(f"{{{m_ns}}}t")))
    rels = {r.get("Id"): r.get("Target") for r in ET.fromstring(z.read("xl/_rels/workbook.xml.rels"))}
    out = {}
    for s in ET.fromstring(z.read("xl/workbook.xml")).find("m:sheets", ns):
        target = rels[s.get(f"{{{r_ns}}}id")]
        target = target if target.startswith("xl/") else "xl/" + target.lstrip("/")
        rows = []
        for row in ET.fromstring(z.read(target)).iter(f"{{{m_ns}}}row"):
            vals = {}
            for c in row.findall("m:c", ns):
                col = re.match(r"[A-Z]+", c.get("r")).group(0)
                v = c.find("m:v", ns)
                if c.get("t") == "s" and v is not None:
                    vals[col] = strings[int(v.text)]
                elif c.get("t") == "inlineStr":
                    vals[col] = "".join(x.text or "" for x in c.iter(f"{{{m_ns}}}t"))
                else:
                    vals[col] = v.text if v is not None else ""
            rows.append(vals)
        out[s.get("name")] = rows
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="compliance/catalog/frameworks")
    out = ap.parse_args().out
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    def prov(url, data, meta):
        return {"source": url, "retrieved_utc": now, "sha256": hashlib.sha256(data).hexdigest(),
                "upstream_version": meta.get("version", ""), "upstream_last_modified": meta.get("last-modified", "")}

    # NIST SP 800-53 Rev 5: every active control and enhancement.
    url = f"{OSCAL}/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json"
    data = fetch(url)
    cat = json.loads(data)["catalog"]
    reqs, known = [], set()
    for depth, cs in sorted(oscal_levels(cat).items()):
        for c, _ in cs:
            reqs.append((label(c), c["title"]))
    order = {g["id"]: i for i, g in enumerate(cat["groups"])}

    def key53(rid):
        m = re.match(r"([A-Z]{2})-(\d+)(?:\((\d+)\))?$", rid)
        return (order.get(m.group(1).lower(), 99), int(m.group(2)), int(m.group(3) or 0))
    reqs.sort(key=lambda r: key53(r[0]))
    known = {r[0] for r in reqs}
    titles53 = dict(reqs)
    write(f"{out}/10-nist-800-53r5.yaml",
          {"id": "nist-800-53r5", "name": "NIST SP 800-53", "version": f"Rev 5 ({cat['metadata'].get('version')})",
           "granularity": "controls and control enhancements (withdrawn excluded)", "source": url},
          reqs, prov(url, data, cat["metadata"]))

    # FedRAMP Rev 5 baselines, cross-checked against 800-53.
    data = fetch(FEDRAMP_XLSX)
    sheets = xlsx_sheets(data)
    for rank, level, sheet in ((20, "low", "Low Baseline"), (21, "moderate", "Moderate Baseline"), (22, "high", "High Baseline")):
        ids = []
        for r in sheets[sheet][2:]:
            rid = re.sub(r"\s+", "", r.get("C", "")).upper()
            if re.match(r"^[A-Z]{2}-\d+(\(\d+\))?$", rid) and rid not in ids:
                ids.append(rid)
        missing = [i for i in ids if i not in known]
        if missing:
            sys.exit(f"FedRAMP {level}: not in 800-53 Rev 5: {missing[:10]}")
        write(f"{out}/{rank}-fedramp-rev5-{level}.yaml",
              {"id": f"fedramp-{level}", "name": f"FedRAMP {level.capitalize()} Baseline", "version": "Rev 5 (legacy workbook)",
               "granularity": "800-53 Rev 5 controls and enhancements in the baseline", "source": FEDRAMP_XLSX,
               "derived_from": "nist-800-53r5"},
              [(i, titles53[i]) for i in ids],
              {"source": FEDRAMP_XLSX, "retrieved_utc": now, "sha256": hashlib.sha256(data).hexdigest(),
               "note": "FedRAMP labels this workbook LEGACY (FedRAMP 20x); Rev 5 baselines unchanged"})

    # CSF 2.0 subcategories, SP 800-171 r3 requirements, SSDF practices.
    # depth counts controls below the top-level groups (functions/families):
    # 0 = CSF categories, 171 requirements, SSDF practices; 1 = CSF
    # subcategories, SSDF tasks.
    for rank, fid, name, ver, path, depth, gran in (
        (50, "nist-csf-2", "NIST Cybersecurity Framework", "2.0", "CSF/v2.0/json/NIST_CSF_v2.0_catalog.json", 1, "subcategories"),
        (60, "nist-800-171r3", "NIST SP 800-171", "Rev 3", "SP800-171/rev3/json/NIST_SP800-171_rev3_catalog.json", 0, "security requirements"),
        (70, "nist-ssdf", "NIST SP 800-218 (SSDF)", "1.1", "SP800-218/ver1/json/NIST_SP800-218_ver1_catalog.json", 0, "practices"),
    ):
        url = f"{OSCAL}/{path}"
        data = fetch(url)
        cat = json.loads(data)["catalog"]
        reqs = []
        for c, parent in oscal_levels(cat).get(depth, []):
            rid = paren_id(label(c))
            title = c.get("title", "")
            if title == rid:  # CSF subcategories carry no title of their own
                title = parent
            reqs.append((rid, title))
        write(f"{out}/{rank}-{fid}.yaml",
              {"id": fid, "name": name, "version": f"{ver} (OSCAL {cat['metadata'].get('version', '')})",
               "granularity": gran, "source": url},
              reqs, prov(url, data, cat["metadata"]))

    csf_references(out, now)


def csf_references(out, now):
    """NIST's own CSF 2.0 informative references (CSF 2.0 Reference Tool
    export), reduced to SP 800-53 and ISO/IEC 27001:2022 per subcategory.
    TestMappingsCorroborated checks controls.yaml against it."""
    data = fetch(CSF_REFS_XLSX)
    rows = xlsx_sheets(data)["CSF 2.0"]
    refs = {}
    for r in rows:
        m = re.match(r"([A-Z]{2}\.[A-Z]{2}-\d{2})", r.get("C", ""))
        if not m:
            continue
        s53, iso = set(), set()
        for line in r.get("E", "").split("\n"):
            mm = re.match(r"SP 800-53 Rev 5\.[0-9.]+: ([A-Z]{2})-0*(\d+)(?:\(0*(\d+)\))?", line)
            if mm:
                s53.add(f"{mm.group(1)}-{mm.group(2)}" + (f"({mm.group(3)})" if mm.group(3) else ""))
            mm = re.match(r"ISO/IEC 27001:2022: (?:Annex A Controls|Control):? (\d+\.\d+)", line)
            if mm:
                iso.add("A." + mm.group(1))
        refs[m.group(1)] = (sorted(s53), sorted(iso))
    lines = ["# GENERATED by scripts/compliance/import-frameworks.py - do not edit by hand.",
             f"# source: {CSF_REFS_XLSX} (NIST CSF 2.0 Reference Tool export)",
             f"# retrieved_utc: {now}",
             f"# sha256: {hashlib.sha256(data).hexdigest()}",
             "# NIST's informative references per CSF 2.0 subcategory, SP 800-53 and",
             "# ISO/IEC 27001:2022 only.",
             "subcategories:"]
    for sub in sorted(refs):
        s53, iso = refs[sub]
        lines.append(f"  {q(sub)}: {{sp800_53: {json.dumps(s53)}, iso27001_2022: {json.dumps(iso)}}}")
    path = f"{out}/../references/nist-csf2-informative.yaml"
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{path}: {len(refs)} subcategories")


if __name__ == "__main__":
    main()
