package cuirass

import (
	"context"
	"fmt"
	"io"
	"sort"
	"strings"
	"sync"
	"testing"
	"time"

	"unheaded/pkg/logger"
)

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

// newTestLogger returns a logger that discards output, suitable for tests.
func newTestLogger() *logger.Logger {
	return logger.New(io.Discard)
}

// newTestService creates a Service with sensible test defaults.
// The wotan client is nil because no network operations are performed.
func newTestService() *Service {
	return NewService(newTestLogger(), nil, nil)
}

// newTestServiceWithConfig creates a Service with a custom config.
func newTestServiceWithConfig(cfg *Config) *Service {
	return NewService(newTestLogger(), nil, cfg)
}

// makeSvc is a convenience for registering a ServiceRegistration with
// reasonable defaults. Only the overridden fields need to be supplied.
func makeSvc(id, name string) *ServiceRegistration {
	return &ServiceRegistration{
		ID:       id,
		Name:     name,
		Version:  "1.0.0",
		Address:  "10.10.10.20",
		Port:     8000,
		Protocol: "http",
	}
}

// ---------------------------------------------------------------------------
// 1. Constructor and Config tests
// ---------------------------------------------------------------------------

func TestDefaultConfig(t *testing.T) {
	t.Parallel()
	cfg := DefaultConfig()

	tests := []struct {
		name     string
		got      interface{}
		expected interface{}
	}{
		{"HealthCheckInterval", cfg.HealthCheckInterval, 10 * time.Second},
		{"ServiceTTL", cfg.ServiceTTL, 30 * time.Second},
		{"DeregisterAfter", cfg.DeregisterAfter, 60 * time.Second},
		{"WotanTopic", cfg.WotanTopic, "cuirass.control"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if tt.got != tt.expected {
				t.Errorf("expected %v, got %v", tt.expected, tt.got)
			}
		})
	}
}

func TestNewService(t *testing.T) {
	t.Parallel()

	t.Run("NilConfig uses defaults", func(t *testing.T) {
		svc := NewService(newTestLogger(), nil, nil)
		if svc == nil {
			t.Fatal("expected non-nil service")
		}
		if svc.config.HealthCheckInterval != 10*time.Second {
			t.Error("expected default HealthCheckInterval")
		}
		if svc.services == nil {
			t.Error("expected services map initialized")
		}
		if svc.clusters == nil {
			t.Error("expected clusters map initialized")
		}
		if svc.health == nil {
			t.Error("expected health map initialized")
		}
	})

	t.Run("CustomConfig is applied", func(t *testing.T) {
		cfg := &Config{
			HealthCheckInterval: 5 * time.Second,
			ServiceTTL:          15 * time.Second,
			DeregisterAfter:     45 * time.Second,
			WotanTopic:         "custom.topic",
		}
		svc := NewService(newTestLogger(), nil, cfg)
		if svc.config.HealthCheckInterval != 5*time.Second {
			t.Error("expected custom HealthCheckInterval")
		}
		if svc.config.WotanTopic != "custom.topic" {
			t.Error("expected custom WotanTopic")
		}
	})
}

// ---------------------------------------------------------------------------
// 2. Start / Stop lifecycle
// ---------------------------------------------------------------------------

func TestStartStop(t *testing.T) {
	t.Parallel()

	svc := newTestService()
	ctx, cancel := context.WithCancel(context.Background())

	if err := svc.Start(ctx); err != nil {
		t.Fatalf("Start returned error: %v", err)
	}

	// Allow background goroutine to start.
	time.Sleep(20 * time.Millisecond)

	// Cancel context to stop the health-check loop.
	cancel()

	if err := svc.Stop(); err != nil {
		t.Fatalf("Stop returned error: %v", err)
	}
}

// ---------------------------------------------------------------------------
// 3. Service Registration -- table-driven
// ---------------------------------------------------------------------------

func TestRegister(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		svc          *ServiceRegistration
		expectID     bool   // expect provided ID to be preserved
		expectStatus ServiceStatus
	}{
		{
			name:         "WithExplicitID",
			svc:          makeSvc("svc-001", "gateway"),
			expectID:     true,
			expectStatus: StatusUnknown,
		},
		{
			name: "WithEmptyID_AutoGenerated",
			svc: &ServiceRegistration{
				Name:     "timeguru",
				Version:  "0.1.0",
				Address:  "10.10.10.21",
				Port:     8001,
				Protocol: "http",
			},
			expectID:     false,
			expectStatus: StatusUnknown,
		},
		{
			name: "WithMetadataAndTags",
			svc: &ServiceRegistration{
				ID:       "svc-meta",
				Name:     "captain",
				Version:  "2.0.0",
				Address:  "10.10.10.22",
				Port:     8002,
				Protocol: "grpc",
				Metadata: map[string]string{"env": "prod"},
				Tags:     []string{"critical", "tier-1"},
			},
			expectID:     true,
			expectStatus: StatusUnknown,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := newTestService()
			ctx := context.Background()

			if err := s.Register(ctx, tt.svc); err != nil {
				t.Fatalf("Register returned error: %v", err)
			}

			if tt.expectID && tt.svc.ID == "" {
				t.Error("expected ID to remain non-empty")
			}
			if !tt.expectID && tt.svc.ID == "" {
				t.Error("expected auto-generated ID")
			}
			if tt.svc.Status != tt.expectStatus {
				t.Errorf("expected status %s, got %s", tt.expectStatus, tt.svc.Status)
			}
			if tt.svc.RegisteredAt.IsZero() {
				t.Error("expected RegisteredAt to be set")
			}
			if tt.svc.LastSeen.IsZero() {
				t.Error("expected LastSeen to be set")
			}

			// Verify retrieval.
			got, ok := s.GetService(tt.svc.ID)
			if !ok {
				t.Fatalf("GetService returned false for registered ID %s", tt.svc.ID)
			}
			if got.Name != tt.svc.Name {
				t.Errorf("expected name %s, got %s", tt.svc.Name, got.Name)
			}
		})
	}
}

func TestRegister_OverwriteExistingID(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	svc1 := makeSvc("dup-001", "serviceA")
	svc2 := makeSvc("dup-001", "serviceB")

	_ = s.Register(ctx, svc1)
	_ = s.Register(ctx, svc2)

	got, ok := s.GetService("dup-001")
	if !ok {
		t.Fatal("expected service to exist after re-register")
	}
	if got.Name != "serviceB" {
		t.Errorf("expected overwritten name 'serviceB', got '%s'", got.Name)
	}
}

// ---------------------------------------------------------------------------
// 4. Deregister
// ---------------------------------------------------------------------------

func TestDeregister(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name      string
		setupIDs  []string
		removeID  string
		expectErr bool
	}{
		{
			name:      "ExistingService",
			setupIDs:  []string{"svc-1"},
			removeID:  "svc-1",
			expectErr: false,
		},
		{
			name:      "NonExistentService",
			setupIDs:  []string{},
			removeID:  "ghost",
			expectErr: true,
		},
		{
			name:      "AlreadyDeregistered",
			setupIDs:  []string{"svc-2"},
			removeID:  "svc-2",
			expectErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := newTestService()
			ctx := context.Background()

			for _, id := range tt.setupIDs {
				_ = s.Register(ctx, makeSvc(id, "test"))
			}

			err := s.Deregister(ctx, tt.removeID)
			if tt.expectErr && err == nil {
				t.Error("expected error, got nil")
			}
			if !tt.expectErr && err != nil {
				t.Errorf("expected no error, got %v", err)
			}

			// Verify removal.
			if !tt.expectErr {
				_, ok := s.GetService(tt.removeID)
				if ok {
					t.Error("service should not be found after deregister")
				}
			}
		})
	}
}

func TestDeregister_CleansUpHealth(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	_ = s.Register(ctx, makeSvc("svc-h", "test"))
	s.RecordHealthCheck(&HealthCheck{
		ServiceID: "svc-h",
		Status:    true,
		Latency:   5,
		CheckedAt: time.Now(),
	})

	// Confirm health exists.
	if _, ok := s.GetHealthCheck("svc-h"); !ok {
		t.Fatal("expected health check to exist before deregister")
	}

	_ = s.Deregister(ctx, "svc-h")

	// Health record should be cleaned up.
	if _, ok := s.GetHealthCheck("svc-h"); ok {
		t.Error("expected health check to be removed after deregister")
	}
}

func TestDeregister_ErrorMessage(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	err := s.Deregister(ctx, "no-such-service")
	if err == nil {
		t.Fatal("expected error for missing service")
	}
	if !strings.Contains(err.Error(), "no-such-service") {
		t.Errorf("error should reference service ID, got: %s", err.Error())
	}
}

// ---------------------------------------------------------------------------
// 5. GetService / GetServiceByName / ListServices
// ---------------------------------------------------------------------------

func TestGetService_NotFound(t *testing.T) {
	t.Parallel()
	s := newTestService()

	_, ok := s.GetService("nonexistent")
	if ok {
		t.Error("expected false for nonexistent service")
	}
}

func TestGetServiceByName(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	// Register three services, two with same name.
	svcs := []*ServiceRegistration{
		makeSvc("a-1", "alpha"),
		makeSvc("a-2", "alpha"),
		makeSvc("b-1", "beta"),
	}
	for _, svc := range svcs {
		_ = s.Register(ctx, svc)
	}

	// GetServiceByName only returns healthy ones, so set status.
	s.RecordHealthCheck(&HealthCheck{ServiceID: "a-1", Status: true, CheckedAt: time.Now()})
	s.RecordHealthCheck(&HealthCheck{ServiceID: "a-2", Status: false, CheckedAt: time.Now()})
	s.RecordHealthCheck(&HealthCheck{ServiceID: "b-1", Status: true, CheckedAt: time.Now()})

	results := s.GetServiceByName("alpha")
	if len(results) != 1 {
		t.Fatalf("expected 1 healthy 'alpha' service, got %d", len(results))
	}
	if results[0].ID != "a-1" {
		t.Errorf("expected ID 'a-1', got '%s'", results[0].ID)
	}
}

func TestGetServiceByName_NoResults(t *testing.T) {
	t.Parallel()
	s := newTestService()

	results := s.GetServiceByName("nonexistent")
	if len(results) != 0 {
		t.Errorf("expected 0 results, got %d", len(results))
	}
}

func TestGetServiceByName_OnlyHealthy(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	_ = s.Register(ctx, makeSvc("u-1", "svc"))
	// Status is unknown after registration; GetServiceByName requires healthy.
	results := s.GetServiceByName("svc")
	if len(results) != 0 {
		t.Errorf("expected 0 results for unknown-status service, got %d", len(results))
	}
}

func TestListServices(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	// Empty initially.
	if len(s.ListServices()) != 0 {
		t.Error("expected 0 services initially")
	}

	// Register three.
	for i := 0; i < 3; i++ {
		_ = s.Register(ctx, makeSvc(fmt.Sprintf("ls-%d", i), "test"))
	}

	list := s.ListServices()
	if len(list) != 3 {
		t.Errorf("expected 3 services, got %d", len(list))
	}
}

// ---------------------------------------------------------------------------
// 6. Heartbeat
// ---------------------------------------------------------------------------

func TestHeartbeat(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name      string
		serviceID string
		register  bool
		expectErr bool
	}{
		{
			name:      "Existing service",
			serviceID: "hb-1",
			register:  true,
			expectErr: false,
		},
		{
			name:      "Non-existent service",
			serviceID: "hb-ghost",
			register:  false,
			expectErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := newTestService()
			ctx := context.Background()

			if tt.register {
				_ = s.Register(ctx, makeSvc(tt.serviceID, "test"))
			}

			// Small sleep to ensure LastSeen differs.
			time.Sleep(5 * time.Millisecond)

			err := s.Heartbeat(ctx, tt.serviceID)
			if tt.expectErr && err == nil {
				t.Error("expected error, got nil")
			}
			if !tt.expectErr && err != nil {
				t.Errorf("expected no error, got %v", err)
			}
		})
	}
}

func TestHeartbeat_UpdatesLastSeen(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	_ = s.Register(ctx, makeSvc("hb-ts", "test"))

	svc, _ := s.GetService("hb-ts")
	beforeHB := svc.LastSeen

	time.Sleep(5 * time.Millisecond)
	_ = s.Heartbeat(ctx, "hb-ts")

	svc, _ = s.GetService("hb-ts")
	if !svc.LastSeen.After(beforeHB) {
		t.Error("expected LastSeen to advance after heartbeat")
	}
}

// ---------------------------------------------------------------------------
// 7. Health checks -- state machine transitions
// ---------------------------------------------------------------------------

func TestRecordHealthCheck(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name           string
		checkStatus    bool
		expectedStatus ServiceStatus
	}{
		{"HealthyCheck", true, StatusHealthy},
		{"UnhealthyCheck", false, StatusUnhealthy},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := newTestService()
			ctx := context.Background()

			_ = s.Register(ctx, makeSvc("hc-1", "test"))

			s.RecordHealthCheck(&HealthCheck{
				ServiceID: "hc-1",
				Status:    tt.checkStatus,
				Latency:   10,
				Message:   "test",
				CheckedAt: time.Now(),
			})

			svc, _ := s.GetService("hc-1")
			if svc.Status != tt.expectedStatus {
				t.Errorf("expected status %s, got %s", tt.expectedStatus, svc.Status)
			}
		})
	}
}

func TestRecordHealthCheck_UpdatesLastSeen(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	_ = s.Register(ctx, makeSvc("hcls-1", "test"))

	svc, _ := s.GetService("hcls-1")
	before := svc.LastSeen

	time.Sleep(5 * time.Millisecond)

	s.RecordHealthCheck(&HealthCheck{
		ServiceID: "hcls-1",
		Status:    true,
		CheckedAt: time.Now(),
	})

	svc, _ = s.GetService("hcls-1")
	if !svc.LastSeen.After(before) {
		t.Error("expected LastSeen to be updated by RecordHealthCheck")
	}
}

func TestRecordHealthCheck_NonExistentService(t *testing.T) {
	t.Parallel()
	s := newTestService()

	// Recording a health check for a service that does not exist should
	// not panic; it stores the check but cannot update service status.
	s.RecordHealthCheck(&HealthCheck{
		ServiceID: "ghost",
		Status:    true,
		CheckedAt: time.Now(),
	})

	check, ok := s.GetHealthCheck("ghost")
	if !ok {
		t.Fatal("expected health check to be stored even for unknown service")
	}
	if !check.Status {
		t.Error("expected check status true")
	}
}

func TestGetHealthCheck_NotFound(t *testing.T) {
	t.Parallel()
	s := newTestService()

	_, ok := s.GetHealthCheck("no-check")
	if ok {
		t.Error("expected false for service with no health check")
	}
}

func TestHealthStatusTransitions(t *testing.T) {
	t.Parallel()

	// Test the full state machine: unknown -> healthy -> unhealthy -> healthy
	s := newTestService()
	ctx := context.Background()

	_ = s.Register(ctx, makeSvc("sm-1", "test"))

	// Initial state is unknown.
	svc, _ := s.GetService("sm-1")
	if svc.Status != StatusUnknown {
		t.Fatalf("expected initial status %s, got %s", StatusUnknown, svc.Status)
	}

	// Transition: unknown -> healthy
	s.RecordHealthCheck(&HealthCheck{ServiceID: "sm-1", Status: true, CheckedAt: time.Now()})
	svc, _ = s.GetService("sm-1")
	if svc.Status != StatusHealthy {
		t.Errorf("expected %s after positive check, got %s", StatusHealthy, svc.Status)
	}

	// Transition: healthy -> unhealthy
	s.RecordHealthCheck(&HealthCheck{ServiceID: "sm-1", Status: false, CheckedAt: time.Now()})
	svc, _ = s.GetService("sm-1")
	if svc.Status != StatusUnhealthy {
		t.Errorf("expected %s after negative check, got %s", StatusUnhealthy, svc.Status)
	}

	// Transition: unhealthy -> healthy (recovery)
	s.RecordHealthCheck(&HealthCheck{ServiceID: "sm-1", Status: true, CheckedAt: time.Now()})
	svc, _ = s.GetService("sm-1")
	if svc.Status != StatusHealthy {
		t.Errorf("expected %s after recovery, got %s", StatusHealthy, svc.Status)
	}
}

func TestServiceStatusConstants(t *testing.T) {
	t.Parallel()

	// Ensure all status values are distinct and non-empty.
	statuses := []ServiceStatus{StatusHealthy, StatusUnhealthy, StatusUnknown, StatusDraining}
	seen := make(map[ServiceStatus]bool)
	for _, s := range statuses {
		if s == "" {
			t.Error("empty status constant found")
		}
		if seen[s] {
			t.Errorf("duplicate status constant: %s", s)
		}
		seen[s] = true
	}
}

// ---------------------------------------------------------------------------
// 8. Cluster management
// ---------------------------------------------------------------------------

func TestRegisterCluster(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		cluster  *Cluster
		expectID bool // true if the provided ID should be preserved
	}{
		{
			name: "WithExplicitID",
			cluster: &Cluster{
				ID:     "cl-001",
				Name:   "us-east-1",
				Region: "us-east",
				Status: "active",
				Nodes: []Node{
					{ID: "n1", Address: "10.0.0.1", Role: "master", Status: "ready"},
				},
			},
			expectID: true,
		},
		{
			name: "AutoGeneratedID",
			cluster: &Cluster{
				Name:   "eu-west-1",
				Region: "eu-west",
				Status: "provisioning",
			},
			expectID: false,
		},
		{
			name: "WithMetadata",
			cluster: &Cluster{
				ID:       "cl-meta",
				Name:     "ap-south-1",
				Region:   "ap-south",
				Status:   "active",
				Metadata: map[string]string{"tier": "premium"},
			},
			expectID: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := newTestService()

			if err := s.RegisterCluster(tt.cluster); err != nil {
				t.Fatalf("RegisterCluster returned error: %v", err)
			}

			if tt.expectID && tt.cluster.ID == "" {
				t.Error("expected provided ID to be preserved")
			}
			if !tt.expectID && tt.cluster.ID == "" {
				t.Error("expected auto-generated cluster ID")
			}

			got, ok := s.GetCluster(tt.cluster.ID)
			if !ok {
				t.Fatal("expected cluster to be retrievable")
			}
			if got.Name != tt.cluster.Name {
				t.Errorf("expected name %s, got %s", tt.cluster.Name, got.Name)
			}
		})
	}
}

func TestGetCluster_NotFound(t *testing.T) {
	t.Parallel()
	s := newTestService()

	_, ok := s.GetCluster("nonexistent")
	if ok {
		t.Error("expected false for nonexistent cluster")
	}
}

func TestListClusters(t *testing.T) {
	t.Parallel()
	s := newTestService()

	if len(s.ListClusters()) != 0 {
		t.Error("expected 0 clusters initially")
	}

	for i := 0; i < 5; i++ {
		_ = s.RegisterCluster(&Cluster{
			ID:     fmt.Sprintf("cl-%d", i),
			Name:   fmt.Sprintf("cluster-%d", i),
			Region: "test",
			Status: "active",
		})
	}

	list := s.ListClusters()
	if len(list) != 5 {
		t.Errorf("expected 5 clusters, got %d", len(list))
	}
}

func TestRegisterCluster_OverwriteExisting(t *testing.T) {
	t.Parallel()
	s := newTestService()

	_ = s.RegisterCluster(&Cluster{ID: "dup-cl", Name: "original", Region: "r1"})
	_ = s.RegisterCluster(&Cluster{ID: "dup-cl", Name: "overwritten", Region: "r2"})

	got, ok := s.GetCluster("dup-cl")
	if !ok {
		t.Fatal("expected cluster to exist")
	}
	if got.Name != "overwritten" {
		t.Errorf("expected overwritten name, got %s", got.Name)
	}
	if got.Region != "r2" {
		t.Errorf("expected overwritten region, got %s", got.Region)
	}
}

// ---------------------------------------------------------------------------
// 9. Stats
// ---------------------------------------------------------------------------

func TestStats_Empty(t *testing.T) {
	t.Parallel()
	s := newTestService()

	stats := s.Stats()
	if stats["total_services"] != 0 {
		t.Errorf("expected 0 total_services, got %v", stats["total_services"])
	}
	if stats["total_clusters"] != 0 {
		t.Errorf("expected 0 total_clusters, got %v", stats["total_clusters"])
	}

	byStatus, ok := stats["by_status"].(map[string]int)
	if !ok {
		t.Fatal("expected by_status to be map[string]int")
	}
	if len(byStatus) != 0 {
		t.Errorf("expected empty by_status, got %v", byStatus)
	}
}

func TestStats_WithMixedStatuses(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	// Register services and set various statuses.
	for i := 0; i < 3; i++ {
		_ = s.Register(ctx, makeSvc(fmt.Sprintf("stat-h-%d", i), "healthy-svc"))
		s.RecordHealthCheck(&HealthCheck{
			ServiceID: fmt.Sprintf("stat-h-%d", i),
			Status:    true,
			CheckedAt: time.Now(),
		})
	}
	for i := 0; i < 2; i++ {
		_ = s.Register(ctx, makeSvc(fmt.Sprintf("stat-u-%d", i), "unhealthy-svc"))
		s.RecordHealthCheck(&HealthCheck{
			ServiceID: fmt.Sprintf("stat-u-%d", i),
			Status:    false,
			CheckedAt: time.Now(),
		})
	}
	_ = s.Register(ctx, makeSvc("stat-unknown", "unknown-svc"))

	// Register a cluster.
	_ = s.RegisterCluster(&Cluster{ID: "stats-cl", Name: "test-cl", Region: "r1"})

	stats := s.Stats()
	if stats["total_services"] != 6 {
		t.Errorf("expected 6 total_services, got %v", stats["total_services"])
	}
	if stats["total_clusters"] != 1 {
		t.Errorf("expected 1 total_clusters, got %v", stats["total_clusters"])
	}

	byStatus := stats["by_status"].(map[string]int)
	if byStatus[string(StatusHealthy)] != 3 {
		t.Errorf("expected 3 healthy, got %d", byStatus[string(StatusHealthy)])
	}
	if byStatus[string(StatusUnhealthy)] != 2 {
		t.Errorf("expected 2 unhealthy, got %d", byStatus[string(StatusUnhealthy)])
	}
	if byStatus[string(StatusUnknown)] != 1 {
		t.Errorf("expected 1 unknown, got %d", byStatus[string(StatusUnknown)])
	}
}

// ---------------------------------------------------------------------------
// 10. Drift detection -- runHealthChecks marks stale services
// ---------------------------------------------------------------------------

func TestRunHealthChecks_MarkUnhealthyPastTTL(t *testing.T) {
	t.Parallel()

	cfg := &Config{
		HealthCheckInterval: 100 * time.Millisecond,
		ServiceTTL:          50 * time.Millisecond,
		DeregisterAfter:     10 * time.Second, // don't deregister
		WotanTopic:         "test",
	}
	s := newTestServiceWithConfig(cfg)
	ctx := context.Background()

	_ = s.Register(ctx, makeSvc("drift-1", "stale-svc"))

	// Make the service healthy initially.
	s.RecordHealthCheck(&HealthCheck{
		ServiceID: "drift-1",
		Status:    true,
		CheckedAt: time.Now(),
	})

	svc, _ := s.GetService("drift-1")
	if svc.Status != StatusHealthy {
		t.Fatalf("expected healthy before drift, got %s", svc.Status)
	}

	// Wait past the TTL so the service becomes stale.
	time.Sleep(cfg.ServiceTTL + 20*time.Millisecond)

	// Run health checks manually.
	s.runHealthChecks(ctx)

	svc, _ = s.GetService("drift-1")
	if svc.Status != StatusUnhealthy {
		t.Errorf("expected unhealthy after TTL expiry, got %s", svc.Status)
	}
}

func TestRunHealthChecks_DeregisterStaleService(t *testing.T) {
	t.Parallel()

	cfg := &Config{
		HealthCheckInterval: 100 * time.Millisecond,
		ServiceTTL:          20 * time.Millisecond,
		DeregisterAfter:     40 * time.Millisecond,
		WotanTopic:         "test",
	}
	s := newTestServiceWithConfig(cfg)
	ctx := context.Background()

	_ = s.Register(ctx, makeSvc("stale-1", "stale-svc"))

	// Wait past the deregister timeout.
	time.Sleep(cfg.DeregisterAfter + 20*time.Millisecond)

	s.runHealthChecks(ctx)

	_, ok := s.GetService("stale-1")
	if ok {
		t.Error("expected stale service to be deregistered")
	}
}

func TestRunHealthChecks_PreservesHealthyServices(t *testing.T) {
	t.Parallel()

	cfg := &Config{
		HealthCheckInterval: 100 * time.Millisecond,
		ServiceTTL:          5 * time.Second,
		DeregisterAfter:     10 * time.Second,
		WotanTopic:         "test",
	}
	s := newTestServiceWithConfig(cfg)
	ctx := context.Background()

	_ = s.Register(ctx, makeSvc("fresh-1", "fresh-svc"))
	s.RecordHealthCheck(&HealthCheck{
		ServiceID: "fresh-1",
		Status:    true,
		CheckedAt: time.Now(),
	})

	s.runHealthChecks(ctx)

	svc, ok := s.GetService("fresh-1")
	if !ok {
		t.Fatal("expected healthy service to still be registered")
	}
	if svc.Status != StatusHealthy {
		t.Errorf("expected healthy status preserved, got %s", svc.Status)
	}
}

// ---------------------------------------------------------------------------
// 11. Reconciliation loop -- integration test with context cancellation
// ---------------------------------------------------------------------------

func TestHealthCheckLoop_ContextCancellation(t *testing.T) {
	t.Parallel()

	cfg := &Config{
		HealthCheckInterval: 20 * time.Millisecond,
		ServiceTTL:          10 * time.Millisecond,
		DeregisterAfter:     30 * time.Millisecond,
		WotanTopic:         "test",
	}
	s := newTestServiceWithConfig(cfg)
	ctx, cancel := context.WithCancel(context.Background())

	_ = s.Register(ctx, makeSvc("loop-1", "loop-svc"))

	// Start the loop directly.
	done := make(chan struct{})
	go func() {
		s.healthCheckLoop(ctx)
		close(done)
	}()

	// Let a few ticks run.
	time.Sleep(80 * time.Millisecond)

	// Cancel and verify clean shutdown.
	cancel()

	select {
	case <-done:
		// Loop exited cleanly.
	case <-time.After(2 * time.Second):
		t.Fatal("healthCheckLoop did not exit after context cancellation")
	}
}

func TestHealthCheckLoop_DeregistersStaleService(t *testing.T) {
	t.Parallel()

	cfg := &Config{
		HealthCheckInterval: 15 * time.Millisecond,
		ServiceTTL:          10 * time.Millisecond,
		DeregisterAfter:     25 * time.Millisecond,
		WotanTopic:         "test",
	}
	s := newTestServiceWithConfig(cfg)
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	_ = s.Register(ctx, makeSvc("loopd-1", "doomed-svc"))

	go s.healthCheckLoop(ctx)

	// Wait long enough for the service to become stale and be deregistered.
	time.Sleep(cfg.DeregisterAfter + 3*cfg.HealthCheckInterval)

	_, ok := s.GetService("loopd-1")
	if ok {
		t.Error("expected service to be deregistered by health check loop")
	}
}

// ---------------------------------------------------------------------------
// 12. Health aggregation
// ---------------------------------------------------------------------------

func TestHealthAggregation_MultipleServices(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	// Register 10 services, half healthy, half unhealthy.
	for i := 0; i < 10; i++ {
		id := fmt.Sprintf("agg-%d", i)
		_ = s.Register(ctx, makeSvc(id, "mixed-svc"))
		s.RecordHealthCheck(&HealthCheck{
			ServiceID: id,
			Status:    i%2 == 0,
			Latency:   int64(i * 5),
			CheckedAt: time.Now(),
		})
	}

	stats := s.Stats()
	byStatus := stats["by_status"].(map[string]int)

	healthy := byStatus[string(StatusHealthy)]
	unhealthy := byStatus[string(StatusUnhealthy)]

	if healthy != 5 {
		t.Errorf("expected 5 healthy, got %d", healthy)
	}
	if unhealthy != 5 {
		t.Errorf("expected 5 unhealthy, got %d", unhealthy)
	}
}

func TestHealthAggregation_AllHealthy(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	for i := 0; i < 5; i++ {
		id := fmt.Sprintf("allh-%d", i)
		_ = s.Register(ctx, makeSvc(id, "svc"))
		s.RecordHealthCheck(&HealthCheck{
			ServiceID: id,
			Status:    true,
			CheckedAt: time.Now(),
		})
	}

	stats := s.Stats()
	byStatus := stats["by_status"].(map[string]int)

	if byStatus[string(StatusHealthy)] != 5 {
		t.Errorf("expected all 5 healthy, got %d", byStatus[string(StatusHealthy)])
	}
	if byStatus[string(StatusUnhealthy)] != 0 {
		t.Errorf("expected 0 unhealthy, got %d", byStatus[string(StatusUnhealthy)])
	}
}

func TestHealthAggregation_AllUnhealthy(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	for i := 0; i < 4; i++ {
		id := fmt.Sprintf("allu-%d", i)
		_ = s.Register(ctx, makeSvc(id, "svc"))
		s.RecordHealthCheck(&HealthCheck{
			ServiceID: id,
			Status:    false,
			CheckedAt: time.Now(),
		})
	}

	stats := s.Stats()
	byStatus := stats["by_status"].(map[string]int)

	if byStatus[string(StatusUnhealthy)] != 4 {
		t.Errorf("expected all 4 unhealthy, got %d", byStatus[string(StatusUnhealthy)])
	}
}

// ---------------------------------------------------------------------------
// 13. Concurrent access -- race-safe tests
// ---------------------------------------------------------------------------

func TestConcurrentRegistrations(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	const goroutines = 50
	var wg sync.WaitGroup
	wg.Add(goroutines)

	for i := 0; i < goroutines; i++ {
		go func(n int) {
			defer wg.Done()
			_ = s.Register(ctx, makeSvc(fmt.Sprintf("conc-%d", n), "concurrent"))
		}(i)
	}
	wg.Wait()

	list := s.ListServices()
	if len(list) != goroutines {
		t.Errorf("expected %d services, got %d", goroutines, len(list))
	}
}

func TestConcurrentRegisterAndDeregister(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	// Pre-register services.
	const total = 100
	for i := 0; i < total; i++ {
		_ = s.Register(ctx, makeSvc(fmt.Sprintf("rd-%d", i), "test"))
	}

	var wg sync.WaitGroup
	wg.Add(total * 2)

	// Half goroutines register, half deregister.
	for i := 0; i < total; i++ {
		go func(n int) {
			defer wg.Done()
			_ = s.Register(ctx, makeSvc(fmt.Sprintf("new-rd-%d", n), "test"))
		}(i)
		go func(n int) {
			defer wg.Done()
			_ = s.Deregister(ctx, fmt.Sprintf("rd-%d", n))
		}(i)
	}
	wg.Wait()

	// All original should be removed, all new ones added.
	list := s.ListServices()
	if len(list) != total {
		t.Errorf("expected %d services after concurrent register/deregister, got %d", total, len(list))
	}
}

func TestConcurrentHealthChecks(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	const total = 30
	for i := 0; i < total; i++ {
		_ = s.Register(ctx, makeSvc(fmt.Sprintf("chc-%d", i), "test"))
	}

	var wg sync.WaitGroup
	wg.Add(total)

	for i := 0; i < total; i++ {
		go func(n int) {
			defer wg.Done()
			s.RecordHealthCheck(&HealthCheck{
				ServiceID: fmt.Sprintf("chc-%d", n),
				Status:    n%2 == 0,
				Latency:   int64(n),
				CheckedAt: time.Now(),
			})
		}(i)
	}
	wg.Wait()

	// Verify no data corruption.
	for i := 0; i < total; i++ {
		check, ok := s.GetHealthCheck(fmt.Sprintf("chc-%d", i))
		if !ok {
			t.Errorf("missing health check for chc-%d", i)
			continue
		}
		expected := i%2 == 0
		if check.Status != expected {
			t.Errorf("chc-%d: expected status %v, got %v", i, expected, check.Status)
		}
	}
}

func TestConcurrentHeartbeats(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	_ = s.Register(ctx, makeSvc("hb-race", "test"))

	const goroutines = 50
	var wg sync.WaitGroup
	wg.Add(goroutines)

	for i := 0; i < goroutines; i++ {
		go func() {
			defer wg.Done()
			_ = s.Heartbeat(ctx, "hb-race")
		}()
	}
	wg.Wait()

	// Service should still exist and be retrievable.
	_, ok := s.GetService("hb-race")
	if !ok {
		t.Error("service should still exist after concurrent heartbeats")
	}
}

func TestConcurrentStatsAndWrites(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	const goroutines = 50
	var wg sync.WaitGroup
	wg.Add(goroutines * 3)

	for i := 0; i < goroutines; i++ {
		go func(n int) {
			defer wg.Done()
			_ = s.Register(ctx, makeSvc(fmt.Sprintf("sw-%d", n), "test"))
		}(i)
		go func(n int) {
			defer wg.Done()
			_ = s.RegisterCluster(&Cluster{
				ID:     fmt.Sprintf("swc-%d", n),
				Name:   fmt.Sprintf("cluster-%d", n),
				Region: "test",
			})
		}(i)
		go func() {
			defer wg.Done()
			_ = s.Stats()
		}()
	}
	wg.Wait()

	// Final stats should be consistent.
	stats := s.Stats()
	if stats["total_services"].(int) != goroutines {
		t.Errorf("expected %d services, got %v", goroutines, stats["total_services"])
	}
	if stats["total_clusters"].(int) != goroutines {
		t.Errorf("expected %d clusters, got %v", goroutines, stats["total_clusters"])
	}
}

func TestConcurrentReadAndWrite(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	const goroutines = 100
	var wg sync.WaitGroup
	wg.Add(goroutines)

	for i := 0; i < goroutines; i++ {
		go func(n int) {
			defer wg.Done()
			switch n % 5 {
			case 0:
				_ = s.Register(ctx, makeSvc(fmt.Sprintf("rw-%d", n), "test"))
			case 1:
				_ = s.ListServices()
			case 2:
				_, _ = s.GetService(fmt.Sprintf("rw-%d", n))
			case 3:
				_ = s.GetServiceByName("test")
			case 4:
				_ = s.Stats()
			}
		}(i)
	}
	wg.Wait()
}

func TestConcurrentClusterOperations(t *testing.T) {
	t.Parallel()
	s := newTestService()

	const goroutines = 40
	var wg sync.WaitGroup
	wg.Add(goroutines)

	for i := 0; i < goroutines; i++ {
		go func(n int) {
			defer wg.Done()
			switch n % 3 {
			case 0:
				_ = s.RegisterCluster(&Cluster{
					ID:     fmt.Sprintf("cc-%d", n),
					Name:   fmt.Sprintf("cluster-%d", n),
					Region: "test",
				})
			case 1:
				_, _ = s.GetCluster(fmt.Sprintf("cc-%d", n))
			case 2:
				_ = s.ListClusters()
			}
		}(i)
	}
	wg.Wait()
}

// ---------------------------------------------------------------------------
// 14. Edge cases and error paths
// ---------------------------------------------------------------------------

func TestDeregister_ThenDeregisterAgain(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	_ = s.Register(ctx, makeSvc("double-d", "test"))
	err := s.Deregister(ctx, "double-d")
	if err != nil {
		t.Fatalf("first deregister should succeed: %v", err)
	}

	err = s.Deregister(ctx, "double-d")
	if err == nil {
		t.Error("second deregister should return error")
	}
}

func TestHeartbeat_AfterDeregister(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	_ = s.Register(ctx, makeSvc("hb-gone", "test"))
	_ = s.Deregister(ctx, "hb-gone")

	err := s.Heartbeat(ctx, "hb-gone")
	if err == nil {
		t.Error("expected error when heartbeating deregistered service")
	}
}

func TestRecordHealthCheck_LatencyValues(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	tests := []struct {
		name    string
		latency int64
	}{
		{"ZeroLatency", 0},
		{"SmallLatency", 1},
		{"LargeLatency", 999999},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			id := fmt.Sprintf("lat-%s", tt.name)
			_ = s.Register(ctx, makeSvc(id, "test"))
			s.RecordHealthCheck(&HealthCheck{
				ServiceID: id,
				Status:    true,
				Latency:   tt.latency,
				CheckedAt: time.Now(),
			})

			check, ok := s.GetHealthCheck(id)
			if !ok {
				t.Fatal("expected health check")
			}
			if check.Latency != tt.latency {
				t.Errorf("expected latency %d, got %d", tt.latency, check.Latency)
			}
		})
	}
}

func TestRegister_SetsTimestamps(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	before := time.Now()
	_ = s.Register(ctx, makeSvc("ts-1", "test"))
	after := time.Now()

	svc, _ := s.GetService("ts-1")
	if svc.RegisteredAt.Before(before) || svc.RegisteredAt.After(after) {
		t.Error("RegisteredAt should be between before and after test timestamps")
	}
	if svc.LastSeen.Before(before) || svc.LastSeen.After(after) {
		t.Error("LastSeen should be between before and after test timestamps")
	}
}

func TestRegister_EmptyName(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	svc := &ServiceRegistration{
		ID:   "empty-name",
		Name: "", // empty name is allowed by the API
	}
	err := s.Register(ctx, svc)
	if err != nil {
		t.Errorf("register with empty name should not error: %v", err)
	}

	got, ok := s.GetService("empty-name")
	if !ok {
		t.Fatal("expected service to exist")
	}
	if got.Name != "" {
		t.Error("expected empty name to be preserved")
	}
}

func TestListServices_DoesNotShareInternalState(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	_ = s.Register(ctx, makeSvc("iso-1", "test"))
	_ = s.Register(ctx, makeSvc("iso-2", "test"))

	list1 := s.ListServices()
	list2 := s.ListServices()

	// Both slices should have the same length.
	if len(list1) != len(list2) {
		t.Fatal("expected same length for two calls to ListServices")
	}

	// The slices themselves should be independent allocations.
	// Modifying one should not affect the other.
	if len(list1) > 0 {
		list1[0] = nil
		if list2[0] == nil {
			t.Error("modifying list1 should not affect list2")
		}
	}
}

func TestListClusters_DoesNotShareInternalState(t *testing.T) {
	t.Parallel()
	s := newTestService()

	_ = s.RegisterCluster(&Cluster{ID: "ciso-1", Name: "c1", Region: "r1"})
	_ = s.RegisterCluster(&Cluster{ID: "ciso-2", Name: "c2", Region: "r1"})

	list1 := s.ListClusters()
	list2 := s.ListClusters()

	if len(list1) > 0 {
		list1[0] = nil
		if list2[0] == nil {
			t.Error("modifying list1 should not affect list2")
		}
	}
}

func TestNodeCapacity(t *testing.T) {
	t.Parallel()
	s := newTestService()

	cluster := &Cluster{
		ID:     "cap-cl",
		Name:   "capacity-test",
		Region: "us-east",
		Nodes: []Node{
			{
				ID:      "n1",
				Address: "10.0.0.1",
				Role:    "master",
				Status:  "ready",
				Capacity: NodeCapacity{
					CPU:     8,
					Memory:  16 * 1024 * 1024 * 1024, // 16GB
					Storage: 100 * 1024 * 1024 * 1024, // 100GB
				},
				Labels: map[string]string{"zone": "a"},
			},
			{
				ID:      "n2",
				Address: "10.0.0.2",
				Role:    "worker",
				Status:  "ready",
				Capacity: NodeCapacity{
					CPU:     16,
					Memory:  32 * 1024 * 1024 * 1024,
					Storage: 500 * 1024 * 1024 * 1024,
				},
			},
		},
	}

	_ = s.RegisterCluster(cluster)

	got, ok := s.GetCluster("cap-cl")
	if !ok {
		t.Fatal("expected cluster to exist")
	}
	if len(got.Nodes) != 2 {
		t.Fatalf("expected 2 nodes, got %d", len(got.Nodes))
	}
	if got.Nodes[0].Capacity.CPU != 8 {
		t.Errorf("expected 8 CPUs for node 0, got %d", got.Nodes[0].Capacity.CPU)
	}
	if got.Nodes[1].Role != "worker" {
		t.Errorf("expected worker role for node 1, got %s", got.Nodes[1].Role)
	}
}

func TestMultipleHealthCheckOverwrite(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	_ = s.Register(ctx, makeSvc("ow-1", "test"))

	// Send three health checks; only the last should be stored.
	for i := 0; i < 3; i++ {
		s.RecordHealthCheck(&HealthCheck{
			ServiceID: "ow-1",
			Status:    i == 2, // only last is true
			Latency:   int64(i * 10),
			Message:   fmt.Sprintf("check-%d", i),
			CheckedAt: time.Now(),
		})
	}

	check, ok := s.GetHealthCheck("ow-1")
	if !ok {
		t.Fatal("expected health check")
	}
	if !check.Status {
		t.Error("expected last health check (true) to be the stored one")
	}
	if check.Latency != 20 {
		t.Errorf("expected latency 20, got %d", check.Latency)
	}
	if check.Message != "check-2" {
		t.Errorf("expected message 'check-2', got '%s'", check.Message)
	}
}

func TestRunHealthChecks_EmptyServiceList(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	// Should not panic on empty service list.
	s.runHealthChecks(ctx)

	if len(s.ListServices()) != 0 {
		t.Error("expected 0 services")
	}
}

func TestRunHealthChecks_MixedStaleness(t *testing.T) {
	t.Parallel()

	cfg := &Config{
		HealthCheckInterval: 100 * time.Millisecond,
		ServiceTTL:          30 * time.Millisecond,
		DeregisterAfter:     60 * time.Millisecond,
		WotanTopic:         "test",
	}
	s := newTestServiceWithConfig(cfg)
	ctx := context.Background()

	// Register two services.
	_ = s.Register(ctx, makeSvc("mix-old", "test"))

	// Wait past the TTL but not DeregisterAfter.
	time.Sleep(cfg.ServiceTTL + 10*time.Millisecond)

	// Register a fresh service.
	_ = s.Register(ctx, makeSvc("mix-new", "test"))
	s.RecordHealthCheck(&HealthCheck{
		ServiceID: "mix-new",
		Status:    true,
		CheckedAt: time.Now(),
	})

	s.runHealthChecks(ctx)

	// Old service should be marked unhealthy.
	oldSvc, ok := s.GetService("mix-old")
	if ok && oldSvc.Status != StatusUnhealthy {
		t.Errorf("expected old service to be unhealthy, got %s", oldSvc.Status)
	}

	// New service should remain healthy.
	newSvc, ok := s.GetService("mix-new")
	if !ok {
		t.Fatal("expected new service to still exist")
	}
	if newSvc.Status != StatusHealthy {
		t.Errorf("expected new service to be healthy, got %s", newSvc.Status)
	}
}

// ---------------------------------------------------------------------------
// 15. Large-scale service registration
// ---------------------------------------------------------------------------

func TestLargeScaleRegistration(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	const count = 1000
	for i := 0; i < count; i++ {
		_ = s.Register(ctx, makeSvc(fmt.Sprintf("large-%d", i), "scale-test"))
	}

	list := s.ListServices()
	if len(list) != count {
		t.Errorf("expected %d services, got %d", count, len(list))
	}

	stats := s.Stats()
	if stats["total_services"].(int) != count {
		t.Errorf("stats: expected %d total, got %v", count, stats["total_services"])
	}
}

// ---------------------------------------------------------------------------
// 16. Service filtering by name and status combinations
// ---------------------------------------------------------------------------

func TestGetServiceByName_MultipleStatuses(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	statuses := []struct {
		id     string
		status bool
	}{
		{"filt-1", true},
		{"filt-2", false},
		{"filt-3", true},
		{"filt-4", false},
		{"filt-5", true},
	}

	for _, st := range statuses {
		_ = s.Register(ctx, makeSvc(st.id, "filterable"))
		s.RecordHealthCheck(&HealthCheck{
			ServiceID: st.id,
			Status:    st.status,
			CheckedAt: time.Now(),
		})
	}

	results := s.GetServiceByName("filterable")
	if len(results) != 3 {
		t.Errorf("expected 3 healthy 'filterable' services, got %d", len(results))
	}

	// All returned should be healthy.
	for _, r := range results {
		if r.Status != StatusHealthy {
			t.Errorf("expected all results to be healthy, got %s for %s", r.Status, r.ID)
		}
	}
}

// ---------------------------------------------------------------------------
// 17. Deterministic ID generation for empty IDs
// ---------------------------------------------------------------------------

func TestAutoGeneratedID_Unique(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	const count = 100
	ids := make(map[string]bool)

	for i := 0; i < count; i++ {
		svc := &ServiceRegistration{
			Name:    "auto-id-test",
			Version: "1.0.0",
		}
		_ = s.Register(ctx, svc)
		if ids[svc.ID] {
			t.Errorf("duplicate auto-generated ID: %s", svc.ID)
		}
		ids[svc.ID] = true
	}

	if len(ids) != count {
		t.Errorf("expected %d unique IDs, got %d", count, len(ids))
	}
}

func TestAutoGeneratedID_ContainsServiceName(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	svc := &ServiceRegistration{
		Name:    "my-service",
		Version: "1.0.0",
	}
	_ = s.Register(ctx, svc)

	if !strings.HasPrefix(svc.ID, "my-service-") {
		t.Errorf("expected auto-generated ID to start with 'my-service-', got '%s'", svc.ID)
	}
}

// ---------------------------------------------------------------------------
// 18. Cluster auto-generated ID
// ---------------------------------------------------------------------------

func TestClusterAutoGeneratedID(t *testing.T) {
	t.Parallel()
	s := newTestService()

	cluster := &Cluster{
		Name:   "auto-cl",
		Region: "us-east",
	}
	_ = s.RegisterCluster(cluster)

	if cluster.ID == "" {
		t.Error("expected non-empty auto-generated cluster ID")
	}
	if !strings.HasPrefix(cluster.ID, "cluster-") {
		t.Errorf("expected cluster ID to start with 'cluster-', got '%s'", cluster.ID)
	}
}

// ---------------------------------------------------------------------------
// 19. Sorted and deterministic list outputs
// ---------------------------------------------------------------------------

func TestListServices_Completeness(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	expected := []string{"ls-a", "ls-b", "ls-c", "ls-d", "ls-e"}
	for _, id := range expected {
		_ = s.Register(ctx, makeSvc(id, "test"))
	}

	list := s.ListServices()
	gotIDs := make([]string, len(list))
	for i, svc := range list {
		gotIDs[i] = svc.ID
	}

	sort.Strings(gotIDs)
	sort.Strings(expected)

	if len(gotIDs) != len(expected) {
		t.Fatalf("expected %d services, got %d", len(expected), len(gotIDs))
	}
	for i := range expected {
		if gotIDs[i] != expected[i] {
			t.Errorf("index %d: expected %s, got %s", i, expected[i], gotIDs[i])
		}
	}
}

func TestListClusters_Completeness(t *testing.T) {
	t.Parallel()
	s := newTestService()

	expected := []string{"lc-a", "lc-b", "lc-c"}
	for _, id := range expected {
		_ = s.RegisterCluster(&Cluster{ID: id, Name: id, Region: "test"})
	}

	list := s.ListClusters()
	gotIDs := make([]string, len(list))
	for i, cl := range list {
		gotIDs[i] = cl.ID
	}

	sort.Strings(gotIDs)
	sort.Strings(expected)

	for i := range expected {
		if gotIDs[i] != expected[i] {
			t.Errorf("index %d: expected %s, got %s", i, expected[i], gotIDs[i])
		}
	}
}

// ---------------------------------------------------------------------------
// 20. Start with context that is already canceled
// ---------------------------------------------------------------------------

func TestStart_AlreadyCanceledContext(t *testing.T) {
	t.Parallel()
	s := newTestService()

	ctx, cancel := context.WithCancel(context.Background())
	cancel() // Cancel before Start.

	err := s.Start(ctx)
	if err != nil {
		t.Fatalf("Start should not error even with canceled context: %v", err)
	}

	// The health-check loop should exit quickly.
	time.Sleep(50 * time.Millisecond)
}

// ---------------------------------------------------------------------------
// 21. Concurrent register, health check, and stats
// ---------------------------------------------------------------------------

func TestConcurrentFullLifecycle(t *testing.T) {
	t.Parallel()
	s := newTestService()
	ctx := context.Background()

	const n = 50
	var wg sync.WaitGroup
	wg.Add(n * 4)

	// Register.
	for i := 0; i < n; i++ {
		go func(idx int) {
			defer wg.Done()
			_ = s.Register(ctx, makeSvc(fmt.Sprintf("fl-%d", idx), "lifecycle"))
		}(i)
	}

	// Heartbeat.
	for i := 0; i < n; i++ {
		go func(idx int) {
			defer wg.Done()
			_ = s.Heartbeat(ctx, fmt.Sprintf("fl-%d", idx))
		}(i)
	}

	// Health check.
	for i := 0; i < n; i++ {
		go func(idx int) {
			defer wg.Done()
			s.RecordHealthCheck(&HealthCheck{
				ServiceID: fmt.Sprintf("fl-%d", idx),
				Status:    idx%3 != 0,
				CheckedAt: time.Now(),
			})
		}(i)
	}

	// Stats + reads.
	for i := 0; i < n; i++ {
		go func(idx int) {
			defer wg.Done()
			_ = s.Stats()
			_ = s.ListServices()
			_ = s.GetServiceByName("lifecycle")
			_, _ = s.GetService(fmt.Sprintf("fl-%d", idx))
			_, _ = s.GetHealthCheck(fmt.Sprintf("fl-%d", idx))
		}(i)
	}

	wg.Wait()
}

// ---------------------------------------------------------------------------
// 22. Service health check message field
// ---------------------------------------------------------------------------

func TestRecordHealthCheck_Message(t *testing.T) {
	t.Parallel()
	s := newTestService()

	s.RecordHealthCheck(&HealthCheck{
		ServiceID: "msg-svc",
		Status:    false,
		Latency:   100,
		Message:   "connection refused",
		CheckedAt: time.Now(),
	})

	check, ok := s.GetHealthCheck("msg-svc")
	if !ok {
		t.Fatal("expected health check to exist")
	}
	if check.Message != "connection refused" {
		t.Errorf("expected message 'connection refused', got '%s'", check.Message)
	}
}

// ---------------------------------------------------------------------------
// 23. Node roles and labels
// ---------------------------------------------------------------------------

func TestCluster_NodeRolesAndLabels(t *testing.T) {
	t.Parallel()
	s := newTestService()

	cluster := &Cluster{
		ID:     "roles-cl",
		Name:   "role-test",
		Region: "us-east",
		Nodes: []Node{
			{
				ID:     "master-1",
				Role:   "master",
				Labels: map[string]string{"zone": "a", "tier": "1"},
			},
			{
				ID:     "worker-1",
				Role:   "worker",
				Labels: map[string]string{"zone": "b", "tier": "2"},
			},
		},
	}

	_ = s.RegisterCluster(cluster)

	got, _ := s.GetCluster("roles-cl")

	for _, node := range got.Nodes {
		if node.Role != "master" && node.Role != "worker" {
			t.Errorf("unexpected role: %s", node.Role)
		}
		if node.Labels == nil {
			t.Error("expected labels to be preserved")
		}
	}
}
