[package]
name        = "canary-ebpf"
description = "Unheaded Protocol canary deployment routing — traffic splitting and metrics collection"
version.workspace   = true
edition.workspace   = true
publish.workspace   = true

[[bin]]
name = "canary-ebpf"
path = "src/main.rs"

[dependencies]
aya-ebpf.workspace     = true
aya-log-ebpf.workspace = true
monad-common.workspace = true
