// SPDX-License-Identifier: MIT
// Copyright (c) 2024-2026 Steven Bellis. All rights reserved.

package observability

import (
	"context"
	"encoding/json"
	"fmt"
	"sync"
	"sync/atomic"
	"time"
)

// FluentdAdapter forwards log entries using the Fluentd forward protocol.
// It buffers events for batch forwarding and generates Fluentd/Fluent Bit
// configuration files.
type FluentdAdapter struct {
	mu        sync.RWMutex
	events    []FluentdEvent
	maxBuffer int
	tag       string
	closed    atomic.Bool
}

// FluentdEvent represents a Fluentd forward protocol event.
type FluentdEvent struct {
	Tag       string            `json:"tag"`
	Timestamp int64             `json:"time"`
	Record    map[string]string `json:"record"`
}

// NewFluentdAdapter creates a Fluentd log forwarding adapter.
// tag sets the base Fluentd tag (e.g. "unheaded.logs").
// maxBuffer limits the in-memory event buffer (0 = unlimited).
func NewFluentdAdapter(tag string, maxBuffer int) *FluentdAdapter {
	if tag == "" {
		tag = "unheaded.logs"
	}
	return &FluentdAdapter{
		tag:       tag,
		maxBuffer: maxBuffer,
	}
}

func (a *FluentdAdapter) Backend() Backend { return BackendFluentd }

func (a *FluentdAdapter) Supports() []SignalType {
	return []SignalType{SignalLog}
}

func (a *FluentdAdapter) EmitMetric(_ context.Context, _ Metric) error {
	return nil
}

func (a *FluentdAdapter) EmitLog(_ context.Context, e LogEntry) error {
	if a.closed.Load() {
		return ErrAdapterClosed
	}

	ts := e.Timestamp
	if ts.IsZero() {
		ts = time.Now()
	}

	record := map[string]string{
		"level":   e.Level,
		"message": e.Message,
		"service": e.Service,
	}
	if e.TraceID != "" {
		record["trace_id"] = e.TraceID
	}
	for k, v := range e.Fields {
		record[k] = v
	}

	event := FluentdEvent{
		Tag:       fmt.Sprintf("%s.%s.%s", a.tag, e.Service, e.Level),
		Timestamp: ts.Unix(),
		Record:    record,
	}

	a.mu.Lock()
	defer a.mu.Unlock()

	if a.maxBuffer > 0 && len(a.events) >= a.maxBuffer {
		a.events = a.events[1:]
	}
	a.events = append(a.events, event)
	return nil
}

func (a *FluentdAdapter) EmitTrace(_ context.Context, _ Span) error {
	return nil
}

func (a *FluentdAdapter) EmitAlert(_ context.Context, _ Alert) error {
	return nil
}

func (a *FluentdAdapter) Close() error {
	a.closed.Store(true)
	return nil
}

// Events returns all buffered events.
func (a *FluentdAdapter) Events() []FluentdEvent {
	a.mu.RLock()
	defer a.mu.RUnlock()
	result := make([]FluentdEvent, len(a.events))
	copy(result, a.events)
	return result
}

// EventCount returns the number of buffered events.
func (a *FluentdAdapter) EventCount() int {
	a.mu.RLock()
	defer a.mu.RUnlock()
	return len(a.events)
}

// JSONPayload returns events in JSON format for the Fluentd HTTP input.
func (a *FluentdAdapter) JSONPayload() string {
	a.mu.RLock()
	defer a.mu.RUnlock()

	data, _ := json.MarshalIndent(a.events, "", "  ")
	return string(data)
}

// FluentdConfig generates a fluentd.conf for an Unheaded service.
func FluentdConfig(service string, outputHost string) string {
	if outputHost == "" {
		outputHost = "localhost"
	}
	return fmt.Sprintf(`# Fluentd config for %s — generated by Unheaded
<source>
  @type forward
  port 24224
  bind 0.0.0.0
  tag unheaded.logs.%s
</source>

<filter unheaded.logs.%s.**>
  @type record_transformer
  <record>
    service %s
    hostname "#{Socket.gethostname}"
  </record>
</filter>

<match unheaded.logs.%s.**>
  @type forward
  <server>
    host %s
    port 24224
  </server>
  <buffer>
    @type file
    path /var/log/fluentd/buffer/%s
    flush_interval 5s
    chunk_limit_size 2M
    total_limit_size 512M
  </buffer>
</match>
`, service, service, service, service, service, outputHost, service)
}

// FluentBitConfig generates a Fluent Bit configuration.
func FluentBitConfig(service string, outputHost string) string {
	if outputHost == "" {
		outputHost = "localhost"
	}
	return fmt.Sprintf(`[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name         tail
    Path         /var/log/unheaded/%s.log
    Tag          unheaded.%s
    Parser       json
    Refresh_Interval 5

[FILTER]
    Name         modify
    Match        unheaded.%s
    Add          service %s

[OUTPUT]
    Name         forward
    Match        unheaded.%s
    Host         %s
    Port         24224
`, service, service, service, service, service, outputHost)
}
