package observability

import (
	"context"
	"encoding/json"
	"fmt"
	"sync"
	"sync/atomic"
	"time"
)

// JaegerAdapter forwards trace spans to a Jaeger collector.
// It buffers spans for batch submission and generates Jaeger agent/collector
// configuration.
type JaegerAdapter struct {
	mu        sync.RWMutex
	spans     []JaegerSpan
	maxBuffer int
	closed    atomic.Bool
}

// JaegerSpan represents a span in Jaeger's data model.
type JaegerSpan struct {
	TraceID       string            `json:"traceID"`
	SpanID        string            `json:"spanID"`
	ParentSpanID  string            `json:"parentSpanID,omitempty"`
	OperationName string            `json:"operationName"`
	ServiceName   string            `json:"serviceName"`
	StartTime     int64             `json:"startTime"` // microseconds
	Duration      int64             `json:"duration"`   // microseconds
	Tags          []JaegerTag       `json:"tags"`
	Logs          []JaegerSpanLog   `json:"logs,omitempty"`
	References    []JaegerReference `json:"references,omitempty"`
}

// JaegerTag is a key-value tag on a span.
type JaegerTag struct {
	Key   string `json:"key"`
	Type  string `json:"type"`
	Value string `json:"value"`
}

// JaegerSpanLog is a timestamped log event on a span.
type JaegerSpanLog struct {
	Timestamp int64       `json:"timestamp"`
	Fields    []JaegerTag `json:"fields"`
}

// JaegerReference links spans in a trace.
type JaegerReference struct {
	RefType string `json:"refType"` // CHILD_OF or FOLLOWS_FROM
	TraceID string `json:"traceID"`
	SpanID  string `json:"spanID"`
}

// NewJaegerAdapter creates a Jaeger tracing adapter.
// maxBuffer limits the in-memory span buffer (0 = unlimited).
func NewJaegerAdapter(maxBuffer int) *JaegerAdapter {
	return &JaegerAdapter{
		maxBuffer: maxBuffer,
	}
}

func (a *JaegerAdapter) Backend() Backend { return BackendJaeger }

func (a *JaegerAdapter) Supports() []SignalType {
	return []SignalType{SignalTrace}
}

func (a *JaegerAdapter) EmitMetric(_ context.Context, _ Metric) error {
	return nil
}

func (a *JaegerAdapter) EmitLog(_ context.Context, _ LogEntry) error {
	return nil
}

func (a *JaegerAdapter) EmitTrace(_ context.Context, s Span) error {
	if a.closed.Load() {
		return ErrAdapterClosed
	}

	startTime := s.StartTime
	if startTime.IsZero() {
		startTime = time.Now()
	}

	jspan := JaegerSpan{
		TraceID:       s.TraceID,
		SpanID:        s.SpanID,
		ParentSpanID:  s.ParentID,
		OperationName: s.Operation,
		ServiceName:   s.Service,
		StartTime:     startTime.UnixMicro(),
		Duration:      s.Duration.Microseconds(),
		Tags: []JaegerTag{
			{Key: "status", Type: "string", Value: string(s.Status)},
		},
	}

	for k, v := range s.Attributes {
		jspan.Tags = append(jspan.Tags, JaegerTag{Key: k, Type: "string", Value: v})
	}

	if s.ParentID != "" {
		jspan.References = []JaegerReference{{
			RefType: "CHILD_OF",
			TraceID: s.TraceID,
			SpanID:  s.ParentID,
		}}
	}

	a.mu.Lock()
	defer a.mu.Unlock()

	if a.maxBuffer > 0 && len(a.spans) >= a.maxBuffer {
		a.spans = a.spans[1:]
	}
	a.spans = append(a.spans, jspan)
	return nil
}

func (a *JaegerAdapter) EmitAlert(_ context.Context, _ Alert) error {
	return nil
}

func (a *JaegerAdapter) Close() error {
	a.closed.Store(true)
	return nil
}

// Spans returns all buffered spans.
func (a *JaegerAdapter) Spans() []JaegerSpan {
	a.mu.RLock()
	defer a.mu.RUnlock()
	result := make([]JaegerSpan, len(a.spans))
	copy(result, a.spans)
	return result
}

// SpanCount returns the number of buffered spans.
func (a *JaegerAdapter) SpanCount() int {
	a.mu.RLock()
	defer a.mu.RUnlock()
	return len(a.spans)
}

// CollectorPayload returns a Jaeger collector API compatible JSON payload.
func (a *JaegerAdapter) CollectorPayload() string {
	a.mu.RLock()
	defer a.mu.RUnlock()

	// Group spans by service
	byService := make(map[string][]JaegerSpan)
	for _, s := range a.spans {
		byService[s.ServiceName] = append(byService[s.ServiceName], s)
	}

	type process struct {
		ServiceName string      `json:"serviceName"`
		Tags        []JaegerTag `json:"tags"`
	}
	type traceData struct {
		Process process      `json:"process"`
		Spans   []JaegerSpan `json:"spans"`
	}

	var data []traceData
	for svc, spans := range byService {
		data = append(data, traceData{
			Process: process{ServiceName: svc},
			Spans:   spans,
		})
	}

	payload, _ := json.MarshalIndent(data, "", "  ")
	return string(payload)
}

// JaegerCollectorConfig generates a Jaeger all-in-one collector configuration.
func JaegerCollectorConfig(esHost string) string {
	if esHost == "" {
		esHost = "localhost:9200"
	}
	return fmt.Sprintf(`# Jaeger Collector config — generated by Unheaded
collector:
  queue-size: 2000
  num-workers: 50
  grpc-server:
    host-port: ":14250"
  http-server:
    host-port: ":14268"
  zipkin:
    host-port: ":9411"

storage:
  type: elasticsearch
  elasticsearch:
    server-urls: http://%s
    index-prefix: unheaded
    tags-as-fields:
      all: true

sampling:
  strategies-file: ""
  initial: 1.0
  type: const
`, esHost)
}
