// SPDX-License-Identifier: MIT
// Copyright (c) 2024-2026 Steven Bellis. All rights reserved.

package observability

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"sync"
	"sync/atomic"
	"time"
)

// LokiAdapter forwards logs to Grafana Loki using the push API format.
// It buffers log streams for batch submission and generates Promtail
// configuration.
type LokiAdapter struct {
	mu        sync.RWMutex
	streams   map[string]*LokiStream
	maxBuffer int
	closed    atomic.Bool
}

// LokiStream represents a Loki log stream identified by label set.
type LokiStream struct {
	Labels  map[string]string `json:"stream"`
	Values  []LokiEntry       `json:"values"`
}

// LokiEntry is a single log line in a Loki stream: [timestamp_ns, line].
type LokiEntry struct {
	TimestampNs string `json:"-"`
	Line        string `json:"-"`
}

// MarshalJSON implements custom JSON for Loki's [timestamp, line] format.
func (e LokiEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal([]string{e.TimestampNs, e.Line})
}

// NewLokiAdapter creates a Loki log aggregation adapter.
// maxBuffer limits entries per stream (0 = unlimited).
func NewLokiAdapter(maxBuffer int) *LokiAdapter {
	return &LokiAdapter{
		streams:   make(map[string]*LokiStream),
		maxBuffer: maxBuffer,
	}
}

func (a *LokiAdapter) Backend() Backend { return BackendLoki }

func (a *LokiAdapter) Supports() []SignalType {
	return []SignalType{SignalLog}
}

func (a *LokiAdapter) EmitMetric(_ context.Context, _ Metric) error {
	return nil
}

func (a *LokiAdapter) EmitLog(_ context.Context, e LogEntry) error {
	if a.closed.Load() {
		return ErrAdapterClosed
	}

	ts := e.Timestamp
	if ts.IsZero() {
		ts = time.Now()
	}

	labels := map[string]string{
		"job": "unheaded",
	}
	if e.Service != "" {
		labels["service"] = e.Service
	}
	if e.Level != "" {
		labels["level"] = e.Level
	}

	streamKey := lokiStreamKey(labels)

	line := e.Message
	if e.TraceID != "" {
		line = fmt.Sprintf("trace_id=%s %s", e.TraceID, line)
	}

	entry := LokiEntry{
		TimestampNs: strconv.FormatInt(ts.UnixNano(), 10),
		Line:        line,
	}

	a.mu.Lock()
	defer a.mu.Unlock()

	stream, ok := a.streams[streamKey]
	if !ok {
		stream = &LokiStream{Labels: labels}
		a.streams[streamKey] = stream
	}

	if a.maxBuffer > 0 && len(stream.Values) >= a.maxBuffer {
		stream.Values = stream.Values[1:]
	}
	stream.Values = append(stream.Values, entry)
	return nil
}

func (a *LokiAdapter) EmitTrace(_ context.Context, _ Span) error {
	return nil
}

func (a *LokiAdapter) EmitAlert(_ context.Context, _ Alert) error {
	return nil
}

func (a *LokiAdapter) Close() error {
	a.closed.Store(true)
	return nil
}

// Streams returns all log streams.
func (a *LokiAdapter) Streams() map[string]*LokiStream {
	a.mu.RLock()
	defer a.mu.RUnlock()
	result := make(map[string]*LokiStream, len(a.streams))
	for k, v := range a.streams {
		cp := &LokiStream{
			Labels: v.Labels,
			Values: make([]LokiEntry, len(v.Values)),
		}
		copy(cp.Values, v.Values)
		result[k] = cp
	}
	return result
}

// StreamCount returns the number of distinct streams.
func (a *LokiAdapter) StreamCount() int {
	a.mu.RLock()
	defer a.mu.RUnlock()
	return len(a.streams)
}

// EntryCount returns the total number of log entries across all streams.
func (a *LokiAdapter) EntryCount() int {
	a.mu.RLock()
	defer a.mu.RUnlock()
	total := 0
	for _, s := range a.streams {
		total += len(s.Values)
	}
	return total
}

// PushPayload returns a Loki push API compatible JSON payload.
func (a *LokiAdapter) PushPayload() string {
	a.mu.RLock()
	defer a.mu.RUnlock()

	type pushRequest struct {
		Streams []*LokiStream `json:"streams"`
	}

	req := pushRequest{}
	for _, s := range a.streams {
		req.Streams = append(req.Streams, s)
	}

	data, _ := json.MarshalIndent(req, "", "  ")
	return string(data)
}

// PromtailConfig generates a Promtail configuration for an Unheaded service.
func PromtailConfig(service string, lokiURL string) string {
	if lokiURL == "" {
		lokiURL = "http://localhost:3100"
	}
	return fmt.Sprintf(`# Promtail config for %s — generated by Unheaded
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions-%s.yaml

clients:
  - url: %s/loki/api/v1/push

scrape_configs:
  - job_name: %s
    static_configs:
      - targets:
          - localhost
        labels:
          job: unheaded
          service: %s
          __path__: /var/log/unheaded/%s.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            trace_id: trace_id
            timestamp: time
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
`, service, service, lokiURL, service, service, service)
}

func lokiStreamKey(labels map[string]string) string {
	keys := make([]string, 0, len(labels))
	for k := range labels {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	key := ""
	for _, k := range keys {
		key += k + "=" + labels[k] + ","
	}
	return key
}
