// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2024-2026 Steven Bellis. All rights reserved.

package observability

import (
	"context"
	"fmt"
	"sync"
	"sync/atomic"
	"time"
)

// NagiosAdapter integrates with Nagios for monitoring and alerting.
// It translates alerts to Nagios passive check results and generates
// host/service check definitions.
type NagiosAdapter struct {
	mu      sync.RWMutex
	checks  []NagiosCheckResult
	closed  atomic.Bool
}

// NagiosCheckResult represents a Nagios passive check result.
type NagiosCheckResult struct {
	Host        string    `json:"host"`
	Service     string    `json:"service"`
	ReturnCode  int       `json:"return_code"` // 0=OK, 1=WARNING, 2=CRITICAL, 3=UNKNOWN
	Output      string    `json:"output"`
	Timestamp   time.Time `json:"timestamp"`
}

// NewNagiosAdapter creates a Nagios monitoring adapter.
func NewNagiosAdapter() *NagiosAdapter {
	return &NagiosAdapter{}
}

func (a *NagiosAdapter) Backend() Backend { return BackendNagios }

func (a *NagiosAdapter) Supports() []SignalType {
	return []SignalType{SignalAlert, SignalMetric}
}

func (a *NagiosAdapter) EmitMetric(_ context.Context, m Metric) error {
	if a.closed.Load() {
		return ErrAdapterClosed
	}

	// Convert metric to Nagios performance data check result
	service := "unknown"
	if s, ok := m.Labels["service"]; ok {
		service = s
	}

	result := NagiosCheckResult{
		Host:       "unheaded",
		Service:    fmt.Sprintf("%s_%s", service, m.Name),
		ReturnCode: 0, // OK
		Output:     fmt.Sprintf("%s=%g | %s=%g", m.Name, m.Value, m.Name, m.Value),
		Timestamp:  m.Timestamp,
	}
	if result.Timestamp.IsZero() {
		result.Timestamp = time.Now()
	}

	a.mu.Lock()
	defer a.mu.Unlock()
	a.checks = append(a.checks, result)
	return nil
}

func (a *NagiosAdapter) EmitLog(_ context.Context, _ LogEntry) error {
	return nil
}

func (a *NagiosAdapter) EmitTrace(_ context.Context, _ Span) error {
	return nil
}

func (a *NagiosAdapter) EmitAlert(_ context.Context, alert Alert) error {
	if a.closed.Load() {
		return ErrAdapterClosed
	}

	ts := alert.Timestamp
	if ts.IsZero() {
		ts = time.Now()
	}

	result := NagiosCheckResult{
		Host:       "unheaded",
		Service:    alert.Service + "_" + alert.Name,
		ReturnCode: severityToNagios(alert.Severity),
		Output:     fmt.Sprintf("[%s] %s", alert.Severity, alert.Message),
		Timestamp:  ts,
	}

	a.mu.Lock()
	defer a.mu.Unlock()
	a.checks = append(a.checks, result)
	return nil
}

func (a *NagiosAdapter) Close() error {
	a.closed.Store(true)
	return nil
}

// CheckResults returns all recorded check results.
func (a *NagiosAdapter) CheckResults() []NagiosCheckResult {
	a.mu.RLock()
	defer a.mu.RUnlock()
	result := make([]NagiosCheckResult, len(a.checks))
	copy(result, a.checks)
	return result
}

// CheckCount returns the number of recorded check results.
func (a *NagiosAdapter) CheckCount() int {
	a.mu.RLock()
	defer a.mu.RUnlock()
	return len(a.checks)
}

// NSCAPayload formats check results for NSCA (Nagios Service Check Acceptor).
func (a *NagiosAdapter) NSCAPayload() string {
	a.mu.RLock()
	defer a.mu.RUnlock()

	var payload string
	for _, c := range a.checks {
		// NSCA format: <host>\t<service>\t<return_code>\t<output>\n
		payload += fmt.Sprintf("%s\t%s\t%d\t%s\n", c.Host, c.Service, c.ReturnCode, c.Output)
	}
	return payload
}

// NagiosServiceDefinition generates a Nagios service check definition.
func NagiosServiceDefinition(service string, port int) string {
	return fmt.Sprintf(`# Nagios service definition — generated by Unheaded
define host {
    use                     linux-server
    host_name               unheaded-%s
    alias                   Unheaded %s Service
    address                 127.0.0.1
    max_check_attempts      5
    check_period            24x7
    notification_interval   30
    notification_period     24x7
}

define service {
    use                     generic-service
    host_name               unheaded-%s
    service_description     %s HTTP Health
    check_command           check_http!-p %d -u /health -e 200
    max_check_attempts      4
    check_interval          1
    retry_interval          1
    check_period            24x7
    notification_interval   30
    notification_period     24x7
    contacts                unheaded-admins
}

define service {
    use                     generic-service
    host_name               unheaded-%s
    service_description     %s Metrics
    check_command           check_http!-p %d -u /metrics -e 200
    max_check_attempts      3
    check_interval          5
    retry_interval          2
    check_period            24x7
    notification_interval   60
    notification_period     24x7
    contacts                unheaded-admins
}
`, service, service, service, service, port, service, service, port)
}

func severityToNagios(s AlertSeverity) int {
	switch s {
	case SeverityInfo:
		return 0 // OK
	case SeverityWarning:
		return 1 // WARNING
	case SeverityError, SeverityCritical:
		return 2 // CRITICAL
	default:
		return 3 // UNKNOWN
	}
}
