apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cuirass-vault-secrets
  namespace: unheaded-armory
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.unheaded-system:8200"
    roleName: "cuirass"
    objects: |
      - objectName: "api-bind-addr"
        secretPath: "unheaded/data/cuirass/config"
        secretKey: "api_bind_addr"
      - objectName: "grpc-bind-addr"
        secretPath: "unheaded/data/cuirass/config"
        secretKey: "grpc_bind_addr"
  secretObjects:
  - secretName: cuirass-config
    type: Opaque
    data:
    - objectName: api-bind-addr
      key: API_BIND_ADDR
    - objectName: grpc-bind-addr
      key: GRPC_BIND_ADDR
