# SPDX-License-Identifier: MIT
# roles/cerydwyn/handlers/main.yml
---
- name: "Restart Ollama"
  ansible.builtin.systemd:
    name: ollama
    state: restarted

- name: "Restart cerydwyn-daemon"
  ansible.builtin.systemd:
    name: cerydwyn-daemon
    state: restarted
