apiVersion: v1
kind: LimitRange
metadata:
  name: armory-limits
  namespace: unheaded-armory
spec:
  limits:
  - default:
      memory: "256Mi"
      cpu: "250m"
    defaultRequest:
      memory: "128Mi"
      cpu: "100m"
    max:
      memory: "1Gi"
      cpu: "1000m"
    type: Container
