apiVersion: v1
kind: Service
metadata:
  name: void-collector
  namespace: unheaded-ebpf
  labels:
    app: void-collector
spec:
  selector:
    app: void-collector
  ports:
  - name: grpc
    port: 9091
    targetPort: grpc
  - name: metrics
    port: 2112
    targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-backend
  namespace: unheaded-presentation
  labels:
    app: dashboard-backend
spec:
  selector:
    app: dashboard-backend
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: websocket
    port: 8081
    targetPort: websocket
  - name: grpc
    port: 9090
    targetPort: grpc
  - name: metrics
    port: 2112
    targetPort: metrics
