apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: void-collector
  namespace: unheaded-ebpf
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: void-collector
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dashboard-backend
  namespace: unheaded-presentation
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: dashboard-backend
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
