// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2024-2026 Steven Bellis. All rights reserved.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: unheaded/v1/protocol.proto

package unheadedv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonadService_Encode_FullMethodName   = "/unheaded.v1.MonadService/Encode"
	MonadService_Decode_FullMethodName   = "/unheaded.v1.MonadService/Decode"
	MonadService_Validate_FullMethodName = "/unheaded.v1.MonadService/Validate"
)

// MonadServiceClient is the client API for MonadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonadServiceClient interface {
	Encode(ctx context.Context, in *EncodeRequest, opts ...grpc.CallOption) (*EncodeResponse, error)
	Decode(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error)
	Validate(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error)
}

type monadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonadServiceClient(cc grpc.ClientConnInterface) MonadServiceClient {
	return &monadServiceClient{cc}
}

func (c *monadServiceClient) Encode(ctx context.Context, in *EncodeRequest, opts ...grpc.CallOption) (*EncodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncodeResponse)
	err := c.cc.Invoke(ctx, MonadService_Encode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monadServiceClient) Decode(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeResponse)
	err := c.cc.Invoke(ctx, MonadService_Decode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monadServiceClient) Validate(ctx context.Context, in *DecodeRequest, opts ...grpc.CallOption) (*DecodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeResponse)
	err := c.cc.Invoke(ctx, MonadService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonadServiceServer is the server API for MonadService service.
// All implementations must embed UnimplementedMonadServiceServer
// for forward compatibility.
type MonadServiceServer interface {
	Encode(context.Context, *EncodeRequest) (*EncodeResponse, error)
	Decode(context.Context, *DecodeRequest) (*DecodeResponse, error)
	Validate(context.Context, *DecodeRequest) (*DecodeResponse, error)
	mustEmbedUnimplementedMonadServiceServer()
}

// UnimplementedMonadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonadServiceServer struct{}

func (UnimplementedMonadServiceServer) Encode(context.Context, *EncodeRequest) (*EncodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Encode not implemented")
}
func (UnimplementedMonadServiceServer) Decode(context.Context, *DecodeRequest) (*DecodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decode not implemented")
}
func (UnimplementedMonadServiceServer) Validate(context.Context, *DecodeRequest) (*DecodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedMonadServiceServer) mustEmbedUnimplementedMonadServiceServer() {}
func (UnimplementedMonadServiceServer) testEmbeddedByValue()                      {}

// UnsafeMonadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonadServiceServer will
// result in compilation errors.
type UnsafeMonadServiceServer interface {
	mustEmbedUnimplementedMonadServiceServer()
}

func RegisterMonadServiceServer(s grpc.ServiceRegistrar, srv MonadServiceServer) {
	// If the following call panics, it indicates UnimplementedMonadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonadService_ServiceDesc, srv)
}

func _MonadService_Encode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonadServiceServer).Encode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonadService_Encode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonadServiceServer).Encode(ctx, req.(*EncodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonadService_Decode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonadServiceServer).Decode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonadService_Decode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonadServiceServer).Decode(ctx, req.(*DecodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonadService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonadServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MonadService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonadServiceServer).Validate(ctx, req.(*DecodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MonadService_ServiceDesc is the grpc.ServiceDesc for MonadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "unheaded.v1.MonadService",
	HandlerType: (*MonadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encode",
			Handler:    _MonadService_Encode_Handler,
		},
		{
			MethodName: "Decode",
			Handler:    _MonadService_Decode_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _MonadService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unheaded/v1/protocol.proto",
}

const (
	SophiaService_List_FullMethodName = "/unheaded.v1.SophiaService/List"
	SophiaService_Get_FullMethodName  = "/unheaded.v1.SophiaService/Get"
)

// SophiaServiceClient is the client API for SophiaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SophiaServiceClient interface {
	List(ctx context.Context, in *DictionaryListRequest, opts ...grpc.CallOption) (*DictionaryListResponse, error)
	Get(ctx context.Context, in *DictionaryGetRequest, opts ...grpc.CallOption) (*DictionaryGetResponse, error)
}

type sophiaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSophiaServiceClient(cc grpc.ClientConnInterface) SophiaServiceClient {
	return &sophiaServiceClient{cc}
}

func (c *sophiaServiceClient) List(ctx context.Context, in *DictionaryListRequest, opts ...grpc.CallOption) (*DictionaryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictionaryListResponse)
	err := c.cc.Invoke(ctx, SophiaService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sophiaServiceClient) Get(ctx context.Context, in *DictionaryGetRequest, opts ...grpc.CallOption) (*DictionaryGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictionaryGetResponse)
	err := c.cc.Invoke(ctx, SophiaService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SophiaServiceServer is the server API for SophiaService service.
// All implementations must embed UnimplementedSophiaServiceServer
// for forward compatibility.
type SophiaServiceServer interface {
	List(context.Context, *DictionaryListRequest) (*DictionaryListResponse, error)
	Get(context.Context, *DictionaryGetRequest) (*DictionaryGetResponse, error)
	mustEmbedUnimplementedSophiaServiceServer()
}

// UnimplementedSophiaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSophiaServiceServer struct{}

func (UnimplementedSophiaServiceServer) List(context.Context, *DictionaryListRequest) (*DictionaryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSophiaServiceServer) Get(context.Context, *DictionaryGetRequest) (*DictionaryGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSophiaServiceServer) mustEmbedUnimplementedSophiaServiceServer() {}
func (UnimplementedSophiaServiceServer) testEmbeddedByValue()                       {}

// UnsafeSophiaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SophiaServiceServer will
// result in compilation errors.
type UnsafeSophiaServiceServer interface {
	mustEmbedUnimplementedSophiaServiceServer()
}

func RegisterSophiaServiceServer(s grpc.ServiceRegistrar, srv SophiaServiceServer) {
	// If the following call panics, it indicates UnimplementedSophiaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SophiaService_ServiceDesc, srv)
}

func _SophiaService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictionaryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SophiaServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SophiaService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SophiaServiceServer).List(ctx, req.(*DictionaryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SophiaService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictionaryGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SophiaServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SophiaService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SophiaServiceServer).Get(ctx, req.(*DictionaryGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SophiaService_ServiceDesc is the grpc.ServiceDesc for SophiaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SophiaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "unheaded.v1.SophiaService",
	HandlerType: (*SophiaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SophiaService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SophiaService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unheaded/v1/protocol.proto",
}

const (
	WotanService_Read_FullMethodName  = "/unheaded.v1.WotanService/Read"
	WotanService_Write_FullMethodName = "/unheaded.v1.WotanService/Write"
)

// WotanServiceClient is the client API for WotanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WotanServiceClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
}

type wotanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWotanServiceClient(cc grpc.ClientConnInterface) WotanServiceClient {
	return &wotanServiceClient{cc}
}

func (c *wotanServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, WotanService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wotanServiceClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, WotanService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WotanServiceServer is the server API for WotanService service.
// All implementations must embed UnimplementedWotanServiceServer
// for forward compatibility.
type WotanServiceServer interface {
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	mustEmbedUnimplementedWotanServiceServer()
}

// UnimplementedWotanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWotanServiceServer struct{}

func (UnimplementedWotanServiceServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedWotanServiceServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedWotanServiceServer) mustEmbedUnimplementedWotanServiceServer() {}
func (UnimplementedWotanServiceServer) testEmbeddedByValue()                      {}

// UnsafeWotanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WotanServiceServer will
// result in compilation errors.
type UnsafeWotanServiceServer interface {
	mustEmbedUnimplementedWotanServiceServer()
}

func RegisterWotanServiceServer(s grpc.ServiceRegistrar, srv WotanServiceServer) {
	// If the following call panics, it indicates UnimplementedWotanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WotanService_ServiceDesc, srv)
}

func _WotanService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WotanServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WotanService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WotanServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WotanService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WotanServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WotanService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WotanServiceServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WotanService_ServiceDesc is the grpc.ServiceDesc for WotanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WotanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "unheaded.v1.WotanService",
	HandlerType: (*WotanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _WotanService_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _WotanService_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unheaded/v1/protocol.proto",
}

const (
	AnamnesisService_Query_FullMethodName  = "/unheaded.v1.AnamnesisService/Query"
	AnamnesisService_Stream_FullMethodName = "/unheaded.v1.AnamnesisService/Stream"
)

// AnamnesisServiceClient is the client API for AnamnesisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnamnesisServiceClient interface {
	Query(ctx context.Context, in *EventQuery, opts ...grpc.CallOption) (*EventQueryResponse, error)
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type anamnesisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnamnesisServiceClient(cc grpc.ClientConnInterface) AnamnesisServiceClient {
	return &anamnesisServiceClient{cc}
}

func (c *anamnesisServiceClient) Query(ctx context.Context, in *EventQuery, opts ...grpc.CallOption) (*EventQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventQueryResponse)
	err := c.cc.Invoke(ctx, AnamnesisService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anamnesisServiceClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnamnesisService_ServiceDesc.Streams[0], AnamnesisService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnamnesisService_StreamClient = grpc.ServerStreamingClient[Event]

// AnamnesisServiceServer is the server API for AnamnesisService service.
// All implementations must embed UnimplementedAnamnesisServiceServer
// for forward compatibility.
type AnamnesisServiceServer interface {
	Query(context.Context, *EventQuery) (*EventQueryResponse, error)
	Stream(*StreamRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedAnamnesisServiceServer()
}

// UnimplementedAnamnesisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnamnesisServiceServer struct{}

func (UnimplementedAnamnesisServiceServer) Query(context.Context, *EventQuery) (*EventQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedAnamnesisServiceServer) Stream(*StreamRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedAnamnesisServiceServer) mustEmbedUnimplementedAnamnesisServiceServer() {}
func (UnimplementedAnamnesisServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnamnesisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnamnesisServiceServer will
// result in compilation errors.
type UnsafeAnamnesisServiceServer interface {
	mustEmbedUnimplementedAnamnesisServiceServer()
}

func RegisterAnamnesisServiceServer(s grpc.ServiceRegistrar, srv AnamnesisServiceServer) {
	// If the following call panics, it indicates UnimplementedAnamnesisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnamnesisService_ServiceDesc, srv)
}

func _AnamnesisService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnamnesisServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnamnesisService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnamnesisServiceServer).Query(ctx, req.(*EventQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnamnesisService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnamnesisServiceServer).Stream(m, &grpc.GenericServerStream[StreamRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnamnesisService_StreamServer = grpc.ServerStreamingServer[Event]

// AnamnesisService_ServiceDesc is the grpc.ServiceDesc for AnamnesisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnamnesisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "unheaded.v1.AnamnesisService",
	HandlerType: (*AnamnesisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _AnamnesisService_Query_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _AnamnesisService_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "unheaded/v1/protocol.proto",
}

const (
	FlowService_List_FullMethodName     = "/unheaded.v1.FlowService/List"
	FlowService_GetState_FullMethodName = "/unheaded.v1.FlowService/GetState"
	FlowService_Inject_FullMethodName   = "/unheaded.v1.FlowService/Inject"
)

// FlowServiceClient is the client API for FlowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlowServiceClient interface {
	List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FlowListResponse, error)
	GetState(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*FlowState, error)
	Inject(ctx context.Context, in *InjectRequest, opts ...grpc.CallOption) (*InjectResponse, error)
}

type flowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowServiceClient(cc grpc.ClientConnInterface) FlowServiceClient {
	return &flowServiceClient{cc}
}

func (c *flowServiceClient) List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FlowListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlowListResponse)
	err := c.cc.Invoke(ctx, FlowService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowServiceClient) GetState(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*FlowState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlowState)
	err := c.cc.Invoke(ctx, FlowService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowServiceClient) Inject(ctx context.Context, in *InjectRequest, opts ...grpc.CallOption) (*InjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectResponse)
	err := c.cc.Invoke(ctx, FlowService_Inject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlowServiceServer is the server API for FlowService service.
// All implementations must embed UnimplementedFlowServiceServer
// for forward compatibility.
type FlowServiceServer interface {
	List(context.Context, *emptypb.Empty) (*FlowListResponse, error)
	GetState(context.Context, *ReadRequest) (*FlowState, error)
	Inject(context.Context, *InjectRequest) (*InjectResponse, error)
	mustEmbedUnimplementedFlowServiceServer()
}

// UnimplementedFlowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlowServiceServer struct{}

func (UnimplementedFlowServiceServer) List(context.Context, *emptypb.Empty) (*FlowListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedFlowServiceServer) GetState(context.Context, *ReadRequest) (*FlowState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedFlowServiceServer) Inject(context.Context, *InjectRequest) (*InjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Inject not implemented")
}
func (UnimplementedFlowServiceServer) mustEmbedUnimplementedFlowServiceServer() {}
func (UnimplementedFlowServiceServer) testEmbeddedByValue()                     {}

// UnsafeFlowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlowServiceServer will
// result in compilation errors.
type UnsafeFlowServiceServer interface {
	mustEmbedUnimplementedFlowServiceServer()
}

func RegisterFlowServiceServer(s grpc.ServiceRegistrar, srv FlowServiceServer) {
	// If the following call panics, it indicates UnimplementedFlowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlowService_ServiceDesc, srv)
}

func _FlowService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowServiceServer).List(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowServiceServer).GetState(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowService_Inject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowServiceServer).Inject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowService_Inject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowServiceServer).Inject(ctx, req.(*InjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlowService_ServiceDesc is the grpc.ServiceDesc for FlowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "unheaded.v1.FlowService",
	HandlerType: (*FlowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _FlowService_List_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _FlowService_GetState_Handler,
		},
		{
			MethodName: "Inject",
			Handler:    _FlowService_Inject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unheaded/v1/protocol.proto",
}
