// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2024-2026 Stevie Bellis. All rights reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: unheaded/v1/protocol.proto

package unheadedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KingdomMode represents the 2-bit state machine for Monad registers
type KingdomMode int32

const (
	KingdomMode_KINGDOM_MODE_UNSPECIFIED KingdomMode = 0
	KingdomMode_KINGDOM_MODE_IDLE        KingdomMode = 1
	KingdomMode_KINGDOM_MODE_ACTIVE      KingdomMode = 2
	KingdomMode_KINGDOM_MODE_CLOSING     KingdomMode = 3
	KingdomMode_KINGDOM_MODE_CLOSED      KingdomMode = 4
)

// Enum value maps for KingdomMode.
var (
	KingdomMode_name = map[int32]string{
		0: "KINGDOM_MODE_UNSPECIFIED",
		1: "KINGDOM_MODE_IDLE",
		2: "KINGDOM_MODE_ACTIVE",
		3: "KINGDOM_MODE_CLOSING",
		4: "KINGDOM_MODE_CLOSED",
	}
	KingdomMode_value = map[string]int32{
		"KINGDOM_MODE_UNSPECIFIED": 0,
		"KINGDOM_MODE_IDLE":        1,
		"KINGDOM_MODE_ACTIVE":      2,
		"KINGDOM_MODE_CLOSING":     3,
		"KINGDOM_MODE_CLOSED":      4,
	}
)

func (x KingdomMode) Enum() *KingdomMode {
	p := new(KingdomMode)
	*p = x
	return p
}

func (x KingdomMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KingdomMode) Descriptor() protoreflect.EnumDescriptor {
	return file_unheaded_v1_protocol_proto_enumTypes[0].Descriptor()
}

func (KingdomMode) Type() protoreflect.EnumType {
	return &file_unheaded_v1_protocol_proto_enumTypes[0]
}

func (x KingdomMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KingdomMode.Descriptor instead.
func (KingdomMode) EnumDescriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{0}
}

type Event_EventType int32

const (
	Event_EVENT_TYPE_UNSPECIFIED     Event_EventType = 0
	Event_EVENT_TYPE_PACKET_RECEIVED Event_EventType = 1
	Event_EVENT_TYPE_PACKET_SENT     Event_EventType = 2
	Event_EVENT_TYPE_FLOW_CREATE     Event_EventType = 3
	Event_EVENT_TYPE_FLOW_UPDATE     Event_EventType = 4
	Event_EVENT_TYPE_FLOW_DESTROY    Event_EventType = 5
	Event_EVENT_TYPE_ERROR           Event_EventType = 6
)

// Enum value maps for Event_EventType.
var (
	Event_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_PACKET_RECEIVED",
		2: "EVENT_TYPE_PACKET_SENT",
		3: "EVENT_TYPE_FLOW_CREATE",
		4: "EVENT_TYPE_FLOW_UPDATE",
		5: "EVENT_TYPE_FLOW_DESTROY",
		6: "EVENT_TYPE_ERROR",
	}
	Event_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":     0,
		"EVENT_TYPE_PACKET_RECEIVED": 1,
		"EVENT_TYPE_PACKET_SENT":     2,
		"EVENT_TYPE_FLOW_CREATE":     3,
		"EVENT_TYPE_FLOW_UPDATE":     4,
		"EVENT_TYPE_FLOW_DESTROY":    5,
		"EVENT_TYPE_ERROR":           6,
	}
)

func (x Event_EventType) Enum() *Event_EventType {
	p := new(Event_EventType)
	*p = x
	return p
}

func (x Event_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_unheaded_v1_protocol_proto_enumTypes[1].Descriptor()
}

func (Event_EventType) Type() protoreflect.EnumType {
	return &file_unheaded_v1_protocol_proto_enumTypes[1]
}

func (x Event_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_EventType.Descriptor instead.
func (Event_EventType) EnumDescriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{16, 0}
}

// MonadRegister represents the complete 20-byte Unheaded Protocol register
// Structure: 20 bytes total, stored in IPv6 Hop-by-Hop extension header
// Bytes 0-17: payload, Bytes 18-19: CRC-16/CCITT-FALSE
type MonadRegister struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flow identifier (20-bit)
	FlowLabel uint32 `protobuf:"varint,1,opt,name=flow_label,json=flowLabel,proto3" json:"flow_label,omitempty"`
	// Kingdom Mode state (2-bit, K1|K0)
	KingdomMode KingdomMode `protobuf:"varint,2,opt,name=kingdom_mode,json=kingdomMode,proto3,enum=unheaded.v1.KingdomMode" json:"kingdom_mode,omitempty"`
	// Timestamp (40-bit unix milliseconds)
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Source address block (128-bit IPv6)
	SourceAddress []byte `protobuf:"bytes,4,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	// Destination address block (128-bit IPv6)
	DestinationAddress []byte `protobuf:"bytes,5,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	// Sophia dictionary identifier (16-bit)
	SophiaDictId uint32 `protobuf:"varint,6,opt,name=sophia_dict_id,json=sophiaDictId,proto3" json:"sophia_dict_id,omitempty"`
	// Wotan sequence number (32-bit)
	WotanSequence uint32 `protobuf:"varint,7,opt,name=wotan_sequence,json=wotanSequence,proto3" json:"wotan_sequence,omitempty"`
	// Reserved field 1 (8-bit)
	Reserved1 uint32 `protobuf:"varint,8,opt,name=reserved1,proto3" json:"reserved1,omitempty"`
	// Reserved field 2 (8-bit)
	Reserved2 uint32 `protobuf:"varint,9,opt,name=reserved2,proto3" json:"reserved2,omitempty"`
	// CRC-16/CCITT-FALSE checksum (16-bit)
	// Computed over bytes 0-17, stored in bytes 18-19
	Crc16         uint32 `protobuf:"varint,10,opt,name=crc16,proto3" json:"crc16,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonadRegister) Reset() {
	*x = MonadRegister{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonadRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonadRegister) ProtoMessage() {}

func (x *MonadRegister) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonadRegister.ProtoReflect.Descriptor instead.
func (*MonadRegister) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *MonadRegister) GetFlowLabel() uint32 {
	if x != nil {
		return x.FlowLabel
	}
	return 0
}

func (x *MonadRegister) GetKingdomMode() KingdomMode {
	if x != nil {
		return x.KingdomMode
	}
	return KingdomMode_KINGDOM_MODE_UNSPECIFIED
}

func (x *MonadRegister) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MonadRegister) GetSourceAddress() []byte {
	if x != nil {
		return x.SourceAddress
	}
	return nil
}

func (x *MonadRegister) GetDestinationAddress() []byte {
	if x != nil {
		return x.DestinationAddress
	}
	return nil
}

func (x *MonadRegister) GetSophiaDictId() uint32 {
	if x != nil {
		return x.SophiaDictId
	}
	return 0
}

func (x *MonadRegister) GetWotanSequence() uint32 {
	if x != nil {
		return x.WotanSequence
	}
	return 0
}

func (x *MonadRegister) GetReserved1() uint32 {
	if x != nil {
		return x.Reserved1
	}
	return 0
}

func (x *MonadRegister) GetReserved2() uint32 {
	if x != nil {
		return x.Reserved2
	}
	return 0
}

func (x *MonadRegister) GetCrc16() uint32 {
	if x != nil {
		return x.Crc16
	}
	return 0
}

// EncodeRequest contains structured fields to encode into wire format
type EncodeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FlowLabel          uint32                 `protobuf:"varint,1,opt,name=flow_label,json=flowLabel,proto3" json:"flow_label,omitempty"`
	KingdomMode        KingdomMode            `protobuf:"varint,2,opt,name=kingdom_mode,json=kingdomMode,proto3,enum=unheaded.v1.KingdomMode" json:"kingdom_mode,omitempty"`
	Timestamp          uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceAddress      []byte                 `protobuf:"bytes,4,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	DestinationAddress []byte                 `protobuf:"bytes,5,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	SophiaDictId       uint32                 `protobuf:"varint,6,opt,name=sophia_dict_id,json=sophiaDictId,proto3" json:"sophia_dict_id,omitempty"`
	WotanSequence      uint32                 `protobuf:"varint,7,opt,name=wotan_sequence,json=wotanSequence,proto3" json:"wotan_sequence,omitempty"`
	Reserved1          uint32                 `protobuf:"varint,8,opt,name=reserved1,proto3" json:"reserved1,omitempty"`
	Reserved2          uint32                 `protobuf:"varint,9,opt,name=reserved2,proto3" json:"reserved2,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EncodeRequest) Reset() {
	*x = EncodeRequest{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeRequest) ProtoMessage() {}

func (x *EncodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeRequest.ProtoReflect.Descriptor instead.
func (*EncodeRequest) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *EncodeRequest) GetFlowLabel() uint32 {
	if x != nil {
		return x.FlowLabel
	}
	return 0
}

func (x *EncodeRequest) GetKingdomMode() KingdomMode {
	if x != nil {
		return x.KingdomMode
	}
	return KingdomMode_KINGDOM_MODE_UNSPECIFIED
}

func (x *EncodeRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EncodeRequest) GetSourceAddress() []byte {
	if x != nil {
		return x.SourceAddress
	}
	return nil
}

func (x *EncodeRequest) GetDestinationAddress() []byte {
	if x != nil {
		return x.DestinationAddress
	}
	return nil
}

func (x *EncodeRequest) GetSophiaDictId() uint32 {
	if x != nil {
		return x.SophiaDictId
	}
	return 0
}

func (x *EncodeRequest) GetWotanSequence() uint32 {
	if x != nil {
		return x.WotanSequence
	}
	return 0
}

func (x *EncodeRequest) GetReserved1() uint32 {
	if x != nil {
		return x.Reserved1
	}
	return 0
}

func (x *EncodeRequest) GetReserved2() uint32 {
	if x != nil {
		return x.Reserved2
	}
	return 0
}

// EncodeResponse contains the raw encoded 20 bytes with computed CRC
type EncodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 20 bytes: bytes 0-17 payload + bytes 18-19 CRC-16
	Crc16         uint32                 `protobuf:"varint,2,opt,name=crc16,proto3" json:"crc16,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeResponse) Reset() {
	*x = EncodeResponse{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeResponse) ProtoMessage() {}

func (x *EncodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeResponse.ProtoReflect.Descriptor instead.
func (*EncodeResponse) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *EncodeResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EncodeResponse) GetCrc16() uint32 {
	if x != nil {
		return x.Crc16
	}
	return 0
}

func (x *EncodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EncodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// DecodeRequest contains raw bytes to decode
type DecodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Must be exactly 20 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeRequest) Reset() {
	*x = DecodeRequest{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeRequest) ProtoMessage() {}

func (x *DecodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeRequest.ProtoReflect.Descriptor instead.
func (*DecodeRequest) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *DecodeRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// DecodeResponse contains decoded fields and validation result
type DecodeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FlowLabel          uint32                 `protobuf:"varint,1,opt,name=flow_label,json=flowLabel,proto3" json:"flow_label,omitempty"`
	KingdomMode        KingdomMode            `protobuf:"varint,2,opt,name=kingdom_mode,json=kingdomMode,proto3,enum=unheaded.v1.KingdomMode" json:"kingdom_mode,omitempty"`
	Timestamp          uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceAddress      []byte                 `protobuf:"bytes,4,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	DestinationAddress []byte                 `protobuf:"bytes,5,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	SophiaDictId       uint32                 `protobuf:"varint,6,opt,name=sophia_dict_id,json=sophiaDictId,proto3" json:"sophia_dict_id,omitempty"`
	WotanSequence      uint32                 `protobuf:"varint,7,opt,name=wotan_sequence,json=wotanSequence,proto3" json:"wotan_sequence,omitempty"`
	Reserved1          uint32                 `protobuf:"varint,8,opt,name=reserved1,proto3" json:"reserved1,omitempty"`
	Reserved2          uint32                 `protobuf:"varint,9,opt,name=reserved2,proto3" json:"reserved2,omitempty"`
	Crc16              uint32                 `protobuf:"varint,10,opt,name=crc16,proto3" json:"crc16,omitempty"`
	Valid              bool                   `protobuf:"varint,11,opt,name=valid,proto3" json:"valid,omitempty"`
	CrcValid           bool                   `protobuf:"varint,12,opt,name=crc_valid,json=crcValid,proto3" json:"crc_valid,omitempty"`
	ErrorMessage       string                 `protobuf:"bytes,13,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DecodeResponse) Reset() {
	*x = DecodeResponse{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeResponse) ProtoMessage() {}

func (x *DecodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeResponse.ProtoReflect.Descriptor instead.
func (*DecodeResponse) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *DecodeResponse) GetFlowLabel() uint32 {
	if x != nil {
		return x.FlowLabel
	}
	return 0
}

func (x *DecodeResponse) GetKingdomMode() KingdomMode {
	if x != nil {
		return x.KingdomMode
	}
	return KingdomMode_KINGDOM_MODE_UNSPECIFIED
}

func (x *DecodeResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DecodeResponse) GetSourceAddress() []byte {
	if x != nil {
		return x.SourceAddress
	}
	return nil
}

func (x *DecodeResponse) GetDestinationAddress() []byte {
	if x != nil {
		return x.DestinationAddress
	}
	return nil
}

func (x *DecodeResponse) GetSophiaDictId() uint32 {
	if x != nil {
		return x.SophiaDictId
	}
	return 0
}

func (x *DecodeResponse) GetWotanSequence() uint32 {
	if x != nil {
		return x.WotanSequence
	}
	return 0
}

func (x *DecodeResponse) GetReserved1() uint32 {
	if x != nil {
		return x.Reserved1
	}
	return 0
}

func (x *DecodeResponse) GetReserved2() uint32 {
	if x != nil {
		return x.Reserved2
	}
	return 0
}

func (x *DecodeResponse) GetCrc16() uint32 {
	if x != nil {
		return x.Crc16
	}
	return 0
}

func (x *DecodeResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *DecodeResponse) GetCrcValid() bool {
	if x != nil {
		return x.CrcValid
	}
	return false
}

func (x *DecodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DictionaryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     uint64                 `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryEntry) Reset() {
	*x = DictionaryEntry{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryEntry) ProtoMessage() {}

func (x *DictionaryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryEntry.ProtoReflect.Descriptor instead.
func (*DictionaryEntry) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *DictionaryEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DictionaryEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DictionaryEntry) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *DictionaryEntry) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Dictionary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Entries       []*DictionaryEntry     `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dictionary) Reset() {
	*x = Dictionary{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dictionary) ProtoMessage() {}

func (x *Dictionary) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dictionary.ProtoReflect.Descriptor instead.
func (*Dictionary) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *Dictionary) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dictionary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dictionary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Dictionary) GetEntries() []*DictionaryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Dictionary) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DictionaryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryListRequest) Reset() {
	*x = DictionaryListRequest{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryListRequest) ProtoMessage() {}

func (x *DictionaryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryListRequest.ProtoReflect.Descriptor instead.
func (*DictionaryListRequest) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *DictionaryListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DictionaryListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DictionaryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dictionaries  []*Dictionary          `protobuf:"bytes,1,rep,name=dictionaries,proto3" json:"dictionaries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryListResponse) Reset() {
	*x = DictionaryListResponse{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryListResponse) ProtoMessage() {}

func (x *DictionaryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryListResponse.ProtoReflect.Descriptor instead.
func (*DictionaryListResponse) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *DictionaryListResponse) GetDictionaries() []*Dictionary {
	if x != nil {
		return x.Dictionaries
	}
	return nil
}

func (x *DictionaryListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DictionaryGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictionaryId  uint32                 `protobuf:"varint,1,opt,name=dictionary_id,json=dictionaryId,proto3" json:"dictionary_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryGetRequest) Reset() {
	*x = DictionaryGetRequest{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryGetRequest) ProtoMessage() {}

func (x *DictionaryGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryGetRequest.ProtoReflect.Descriptor instead.
func (*DictionaryGetRequest) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *DictionaryGetRequest) GetDictionaryId() uint32 {
	if x != nil {
		return x.DictionaryId
	}
	return 0
}

type DictionaryGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dictionary    *Dictionary            `protobuf:"bytes,1,opt,name=dictionary,proto3" json:"dictionary,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryGetResponse) Reset() {
	*x = DictionaryGetResponse{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryGetResponse) ProtoMessage() {}

func (x *DictionaryGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryGetResponse.ProtoReflect.Descriptor instead.
func (*DictionaryGetResponse) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *DictionaryGetResponse) GetDictionary() *Dictionary {
	if x != nil {
		return x.Dictionary
	}
	return nil
}

func (x *DictionaryGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *DictionaryGetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type MemorySlot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FlowLabel      uint32                 `protobuf:"varint,1,opt,name=flow_label,json=flowLabel,proto3" json:"flow_label,omitempty"`
	StateData      []byte                 `protobuf:"bytes,2,opt,name=state_data,json=stateData,proto3" json:"state_data,omitempty"`                 // 32 bytes of opaque state
	SequenceNumber uint64                 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // 8 bytes of sequence metadata
	CreatedAt      uint64                 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      uint64                 `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemorySlot) Reset() {
	*x = MemorySlot{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemorySlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemorySlot) ProtoMessage() {}

func (x *MemorySlot) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemorySlot.ProtoReflect.Descriptor instead.
func (*MemorySlot) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *MemorySlot) GetFlowLabel() uint32 {
	if x != nil {
		return x.FlowLabel
	}
	return 0
}

func (x *MemorySlot) GetStateData() []byte {
	if x != nil {
		return x.StateData
	}
	return nil
}

func (x *MemorySlot) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MemorySlot) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MemorySlot) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowLabel     uint32                 `protobuf:"varint,1,opt,name=flow_label,json=flowLabel,proto3" json:"flow_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *ReadRequest) GetFlowLabel() uint32 {
	if x != nil {
		return x.FlowLabel
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          *MemorySlot            `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *ReadResponse) GetSlot() *MemorySlot {
	if x != nil {
		return x.Slot
	}
	return nil
}

func (x *ReadResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ReadResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type WriteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FlowLabel      uint32                 `protobuf:"varint,1,opt,name=flow_label,json=flowLabel,proto3" json:"flow_label,omitempty"`
	StateData      []byte                 `protobuf:"bytes,2,opt,name=state_data,json=stateData,proto3" json:"state_data,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *WriteRequest) GetFlowLabel() uint32 {
	if x != nil {
		return x.FlowLabel
	}
	return 0
}

func (x *WriteRequest) GetStateData() []byte {
	if x != nil {
		return x.StateData
	}
	return nil
}

func (x *WriteRequest) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowLabel     uint32                 `protobuf:"varint,1,opt,name=flow_label,json=flowLabel,proto3" json:"flow_label,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	WrittenAt     uint64                 `protobuf:"varint,4,opt,name=written_at,json=writtenAt,proto3" json:"written_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *WriteResponse) GetFlowLabel() uint32 {
	if x != nil {
		return x.FlowLabel
	}
	return 0
}

func (x *WriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WriteResponse) GetWrittenAt() uint64 {
	if x != nil {
		return x.WrittenAt
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Event_EventType        `protobuf:"varint,1,opt,name=type,proto3,enum=unheaded.v1.Event_EventType" json:"type,omitempty"`
	FlowLabel     uint32                 `protobuf:"varint,2,opt,name=flow_label,json=flowLabel,proto3" json:"flow_label,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *Event) GetType() Event_EventType {
	if x != nil {
		return x.Type
	}
	return Event_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetFlowLabel() uint32 {
	if x != nil {
		return x.FlowLabel
	}
	return 0
}

func (x *Event) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EventQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix milliseconds
	EndTime       int64                  `protobuf:"varint,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	FlowLabels    []uint32               `protobuf:"varint,3,rep,packed,name=flow_labels,json=flowLabels,proto3" json:"flow_labels,omitempty"`                                  // Filter by specific flow labels
	EventTypes    []Event_EventType      `protobuf:"varint,4,rep,packed,name=event_types,json=eventTypes,proto3,enum=unheaded.v1.Event_EventType" json:"event_types,omitempty"` // Filter by event types
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventQuery) Reset() {
	*x = EventQuery{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventQuery) ProtoMessage() {}

func (x *EventQuery) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventQuery.ProtoReflect.Descriptor instead.
func (*EventQuery) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{17}
}

func (x *EventQuery) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *EventQuery) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *EventQuery) GetFlowLabels() []uint32 {
	if x != nil {
		return x.FlowLabels
	}
	return nil
}

func (x *EventQuery) GetEventTypes() []Event_EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *EventQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *EventQuery) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type EventQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventQueryResponse) Reset() {
	*x = EventQueryResponse{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventQueryResponse) ProtoMessage() {}

func (x *EventQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventQueryResponse.ProtoReflect.Descriptor instead.
func (*EventQueryResponse) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{18}
}

func (x *EventQueryResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventQueryResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *EventQueryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StreamRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FlowLabels        []uint32               `protobuf:"varint,1,rep,packed,name=flow_labels,json=flowLabels,proto3" json:"flow_labels,omitempty"` // Subscribe to specific flows
	EventTypes        []Event_EventType      `protobuf:"varint,2,rep,packed,name=event_types,json=eventTypes,proto3,enum=unheaded.v1.Event_EventType" json:"event_types,omitempty"`
	IncludeHistorical bool                   `protobuf:"varint,3,opt,name=include_historical,json=includeHistorical,proto3" json:"include_historical,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{19}
}

func (x *StreamRequest) GetFlowLabels() []uint32 {
	if x != nil {
		return x.FlowLabels
	}
	return nil
}

func (x *StreamRequest) GetEventTypes() []Event_EventType {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *StreamRequest) GetIncludeHistorical() bool {
	if x != nil {
		return x.IncludeHistorical
	}
	return false
}

type FlowState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FlowLabel          uint32                 `protobuf:"varint,1,opt,name=flow_label,json=flowLabel,proto3" json:"flow_label,omitempty"`
	KingdomMode        KingdomMode            `protobuf:"varint,2,opt,name=kingdom_mode,json=kingdomMode,proto3,enum=unheaded.v1.KingdomMode" json:"kingdom_mode,omitempty"`
	SophiaDictId       uint32                 `protobuf:"varint,3,opt,name=sophia_dict_id,json=sophiaDictId,proto3" json:"sophia_dict_id,omitempty"`
	WotanSequence      uint32                 `protobuf:"varint,4,opt,name=wotan_sequence,json=wotanSequence,proto3" json:"wotan_sequence,omitempty"`
	SourceAddress      []byte                 `protobuf:"bytes,5,opt,name=source_address,json=sourceAddress,proto3" json:"source_address,omitempty"`
	DestinationAddress []byte                 `protobuf:"bytes,6,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	CreatedAt          uint64                 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          uint64                 `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastPacketAt       uint64                 `protobuf:"varint,9,opt,name=last_packet_at,json=lastPacketAt,proto3" json:"last_packet_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FlowState) Reset() {
	*x = FlowState{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowState) ProtoMessage() {}

func (x *FlowState) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowState.ProtoReflect.Descriptor instead.
func (*FlowState) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{20}
}

func (x *FlowState) GetFlowLabel() uint32 {
	if x != nil {
		return x.FlowLabel
	}
	return 0
}

func (x *FlowState) GetKingdomMode() KingdomMode {
	if x != nil {
		return x.KingdomMode
	}
	return KingdomMode_KINGDOM_MODE_UNSPECIFIED
}

func (x *FlowState) GetSophiaDictId() uint32 {
	if x != nil {
		return x.SophiaDictId
	}
	return 0
}

func (x *FlowState) GetWotanSequence() uint32 {
	if x != nil {
		return x.WotanSequence
	}
	return 0
}

func (x *FlowState) GetSourceAddress() []byte {
	if x != nil {
		return x.SourceAddress
	}
	return nil
}

func (x *FlowState) GetDestinationAddress() []byte {
	if x != nil {
		return x.DestinationAddress
	}
	return nil
}

func (x *FlowState) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FlowState) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *FlowState) GetLastPacketAt() uint64 {
	if x != nil {
		return x.LastPacketAt
	}
	return 0
}

type FlowListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flows         []*FlowState           `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowListResponse) Reset() {
	*x = FlowListResponse{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowListResponse) ProtoMessage() {}

func (x *FlowListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowListResponse.ProtoReflect.Descriptor instead.
func (*FlowListResponse) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{21}
}

func (x *FlowListResponse) GetFlows() []*FlowState {
	if x != nil {
		return x.Flows
	}
	return nil
}

func (x *FlowListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FlowListResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type InjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowLabel     uint32                 `protobuf:"varint,1,opt,name=flow_label,json=flowLabel,proto3" json:"flow_label,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	KingdomMode   KingdomMode            `protobuf:"varint,3,opt,name=kingdom_mode,json=kingdomMode,proto3,enum=unheaded.v1.KingdomMode" json:"kingdom_mode,omitempty"`
	SophiaDictId  uint32                 `protobuf:"varint,4,opt,name=sophia_dict_id,json=sophiaDictId,proto3" json:"sophia_dict_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectRequest) Reset() {
	*x = InjectRequest{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectRequest) ProtoMessage() {}

func (x *InjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectRequest.ProtoReflect.Descriptor instead.
func (*InjectRequest) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{22}
}

func (x *InjectRequest) GetFlowLabel() uint32 {
	if x != nil {
		return x.FlowLabel
	}
	return 0
}

func (x *InjectRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InjectRequest) GetKingdomMode() KingdomMode {
	if x != nil {
		return x.KingdomMode
	}
	return KingdomMode_KINGDOM_MODE_UNSPECIFIED
}

func (x *InjectRequest) GetSophiaDictId() uint32 {
	if x != nil {
		return x.SophiaDictId
	}
	return 0
}

type InjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      string                 `protobuf:"bytes,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	InjectedAt    uint64                 `protobuf:"varint,2,opt,name=injected_at,json=injectedAt,proto3" json:"injected_at,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectResponse) Reset() {
	*x = InjectResponse{}
	mi := &file_unheaded_v1_protocol_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectResponse) ProtoMessage() {}

func (x *InjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_unheaded_v1_protocol_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectResponse.ProtoReflect.Descriptor instead.
func (*InjectResponse) Descriptor() ([]byte, []int) {
	return file_unheaded_v1_protocol_proto_rawDescGZIP(), []int{23}
}

func (x *InjectResponse) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

func (x *InjectResponse) GetInjectedAt() uint64 {
	if x != nil {
		return x.InjectedAt
	}
	return 0
}

func (x *InjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InjectResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_unheaded_v1_protocol_proto protoreflect.FileDescriptor

const file_unheaded_v1_protocol_proto_rawDesc = "" +
	"\n" +
	"\x1aunheaded/v1/protocol.proto\x12\vunheaded.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x80\x03\n" +
	"\rMonadRegister\x12\x1d\n" +
	"\n" +
	"flow_label\x18\x01 \x01(\rR\tflowLabel\x12;\n" +
	"\fkingdom_mode\x18\x02 \x01(\x0e2\x18.unheaded.v1.KingdomModeR\vkingdomMode\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12%\n" +
	"\x0esource_address\x18\x04 \x01(\fR\rsourceAddress\x12/\n" +
	"\x13destination_address\x18\x05 \x01(\fR\x12destinationAddress\x12$\n" +
	"\x0esophia_dict_id\x18\x06 \x01(\rR\fsophiaDictId\x12%\n" +
	"\x0ewotan_sequence\x18\a \x01(\rR\rwotanSequence\x12\x1c\n" +
	"\treserved1\x18\b \x01(\rR\treserved1\x12\x1c\n" +
	"\treserved2\x18\t \x01(\rR\treserved2\x12\x14\n" +
	"\x05crc16\x18\n" +
	" \x01(\rR\x05crc16\"\xea\x02\n" +
	"\rEncodeRequest\x12\x1d\n" +
	"\n" +
	"flow_label\x18\x01 \x01(\rR\tflowLabel\x12;\n" +
	"\fkingdom_mode\x18\x02 \x01(\x0e2\x18.unheaded.v1.KingdomModeR\vkingdomMode\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12%\n" +
	"\x0esource_address\x18\x04 \x01(\fR\rsourceAddress\x12/\n" +
	"\x13destination_address\x18\x05 \x01(\fR\x12destinationAddress\x12$\n" +
	"\x0esophia_dict_id\x18\x06 \x01(\rR\fsophiaDictId\x12%\n" +
	"\x0ewotan_sequence\x18\a \x01(\rR\rwotanSequence\x12\x1c\n" +
	"\treserved1\x18\b \x01(\rR\treserved1\x12\x1c\n" +
	"\treserved2\x18\t \x01(\rR\treserved2\"y\n" +
	"\x0eEncodeResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05crc16\x18\x02 \x01(\rR\x05crc16\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"#\n" +
	"\rDecodeRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xd9\x03\n" +
	"\x0eDecodeResponse\x12\x1d\n" +
	"\n" +
	"flow_label\x18\x01 \x01(\rR\tflowLabel\x12;\n" +
	"\fkingdom_mode\x18\x02 \x01(\x0e2\x18.unheaded.v1.KingdomModeR\vkingdomMode\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12%\n" +
	"\x0esource_address\x18\x04 \x01(\fR\rsourceAddress\x12/\n" +
	"\x13destination_address\x18\x05 \x01(\fR\x12destinationAddress\x12$\n" +
	"\x0esophia_dict_id\x18\x06 \x01(\rR\fsophiaDictId\x12%\n" +
	"\x0ewotan_sequence\x18\a \x01(\rR\rwotanSequence\x12\x1c\n" +
	"\treserved1\x18\b \x01(\rR\treserved1\x12\x1c\n" +
	"\treserved2\x18\t \x01(\rR\treserved2\x12\x14\n" +
	"\x05crc16\x18\n" +
	" \x01(\rR\x05crc16\x12\x14\n" +
	"\x05valid\x18\v \x01(\bR\x05valid\x12\x1b\n" +
	"\tcrc_valid\x18\f \x01(\bR\bcrcValid\x12#\n" +
	"\rerror_message\x18\r \x01(\tR\ferrorMessage\"w\n" +
	"\x0fDictionaryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x04R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x04R\tupdatedAt\"\xa9\x01\n" +
	"\n" +
	"Dictionary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x126\n" +
	"\aentries\x18\x04 \x03(\v2\x1c.unheaded.v1.DictionaryEntryR\aentries\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x04R\tcreatedAt\"E\n" +
	"\x15DictionaryListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"k\n" +
	"\x16DictionaryListResponse\x12;\n" +
	"\fdictionaries\x18\x01 \x03(\v2\x17.unheaded.v1.DictionaryR\fdictionaries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\";\n" +
	"\x14DictionaryGetRequest\x12#\n" +
	"\rdictionary_id\x18\x01 \x01(\rR\fdictionaryId\"\x8b\x01\n" +
	"\x15DictionaryGetResponse\x127\n" +
	"\n" +
	"dictionary\x18\x01 \x01(\v2\x17.unheaded.v1.DictionaryR\n" +
	"dictionary\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xb1\x01\n" +
	"\n" +
	"MemorySlot\x12\x1d\n" +
	"\n" +
	"flow_label\x18\x01 \x01(\rR\tflowLabel\x12\x1d\n" +
	"\n" +
	"state_data\x18\x02 \x01(\fR\tstateData\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x04R\x0esequenceNumber\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x04R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x04R\tupdatedAt\",\n" +
	"\vReadRequest\x12\x1d\n" +
	"\n" +
	"flow_label\x18\x01 \x01(\rR\tflowLabel\"v\n" +
	"\fReadResponse\x12+\n" +
	"\x04slot\x18\x01 \x01(\v2\x17.unheaded.v1.MemorySlotR\x04slot\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"u\n" +
	"\fWriteRequest\x12\x1d\n" +
	"\n" +
	"flow_label\x18\x01 \x01(\rR\tflowLabel\x12\x1d\n" +
	"\n" +
	"state_data\x18\x02 \x01(\fR\tstateData\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x04R\x0esequenceNumber\"\x8c\x01\n" +
	"\rWriteResponse\x12\x1d\n" +
	"\n" +
	"flow_label\x18\x01 \x01(\rR\tflowLabel\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"written_at\x18\x04 \x01(\x04R\twrittenAt\"\xf4\x03\n" +
	"\x05Event\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.unheaded.v1.Event.EventTypeR\x04type\x12\x1d\n" +
	"\n" +
	"flow_label\x18\x02 \x01(\rR\tflowLabel\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12<\n" +
	"\bmetadata\x18\x06 \x03(\v2 .unheaded.v1.Event.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aEVENT_TYPE_PACKET_RECEIVED\x10\x01\x12\x1a\n" +
	"\x16EVENT_TYPE_PACKET_SENT\x10\x02\x12\x1a\n" +
	"\x16EVENT_TYPE_FLOW_CREATE\x10\x03\x12\x1a\n" +
	"\x16EVENT_TYPE_FLOW_UPDATE\x10\x04\x12\x1b\n" +
	"\x17EVENT_TYPE_FLOW_DESTROY\x10\x05\x12\x14\n" +
	"\x10EVENT_TYPE_ERROR\x10\x06\"\xd4\x01\n" +
	"\n" +
	"EventQuery\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x03R\aendTime\x12\x1f\n" +
	"\vflow_labels\x18\x03 \x03(\rR\n" +
	"flowLabels\x12=\n" +
	"\vevent_types\x18\x04 \x03(\x0e2\x1c.unheaded.v1.Event.EventTypeR\n" +
	"eventTypes\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"\x86\x01\n" +
	"\x12EventQueryResponse\x12*\n" +
	"\x06events\x18\x01 \x03(\v2\x12.unheaded.v1.EventR\x06events\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x9e\x01\n" +
	"\rStreamRequest\x12\x1f\n" +
	"\vflow_labels\x18\x01 \x03(\rR\n" +
	"flowLabels\x12=\n" +
	"\vevent_types\x18\x02 \x03(\x0e2\x1c.unheaded.v1.Event.EventTypeR\n" +
	"eventTypes\x12-\n" +
	"\x12include_historical\x18\x03 \x01(\bR\x11includeHistorical\"\xf0\x02\n" +
	"\tFlowState\x12\x1d\n" +
	"\n" +
	"flow_label\x18\x01 \x01(\rR\tflowLabel\x12;\n" +
	"\fkingdom_mode\x18\x02 \x01(\x0e2\x18.unheaded.v1.KingdomModeR\vkingdomMode\x12$\n" +
	"\x0esophia_dict_id\x18\x03 \x01(\rR\fsophiaDictId\x12%\n" +
	"\x0ewotan_sequence\x18\x04 \x01(\rR\rwotanSequence\x12%\n" +
	"\x0esource_address\x18\x05 \x01(\fR\rsourceAddress\x12/\n" +
	"\x13destination_address\x18\x06 \x01(\fR\x12destinationAddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x04R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x04R\tupdatedAt\x12$\n" +
	"\x0elast_packet_at\x18\t \x01(\x04R\flastPacketAt\"{\n" +
	"\x10FlowListResponse\x12,\n" +
	"\x05flows\x18\x01 \x03(\v2\x16.unheaded.v1.FlowStateR\x05flows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xab\x01\n" +
	"\rInjectRequest\x12\x1d\n" +
	"\n" +
	"flow_label\x18\x01 \x01(\rR\tflowLabel\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12;\n" +
	"\fkingdom_mode\x18\x03 \x01(\x0e2\x18.unheaded.v1.KingdomModeR\vkingdomMode\x12$\n" +
	"\x0esophia_dict_id\x18\x04 \x01(\rR\fsophiaDictId\"\x8d\x01\n" +
	"\x0eInjectResponse\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\tR\bpacketId\x12\x1f\n" +
	"\vinjected_at\x18\x02 \x01(\x04R\n" +
	"injectedAt\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage*\x8e\x01\n" +
	"\vKingdomMode\x12\x1c\n" +
	"\x18KINGDOM_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11KINGDOM_MODE_IDLE\x10\x01\x12\x17\n" +
	"\x13KINGDOM_MODE_ACTIVE\x10\x02\x12\x18\n" +
	"\x14KINGDOM_MODE_CLOSING\x10\x03\x12\x17\n" +
	"\x13KINGDOM_MODE_CLOSED\x10\x042\xd9\x01\n" +
	"\fMonadService\x12A\n" +
	"\x06Encode\x12\x1a.unheaded.v1.EncodeRequest\x1a\x1b.unheaded.v1.EncodeResponse\x12A\n" +
	"\x06Decode\x12\x1a.unheaded.v1.DecodeRequest\x1a\x1b.unheaded.v1.DecodeResponse\x12C\n" +
	"\bValidate\x12\x1a.unheaded.v1.DecodeRequest\x1a\x1b.unheaded.v1.DecodeResponse2\xae\x01\n" +
	"\rSophiaService\x12O\n" +
	"\x04List\x12\".unheaded.v1.DictionaryListRequest\x1a#.unheaded.v1.DictionaryListResponse\x12L\n" +
	"\x03Get\x12!.unheaded.v1.DictionaryGetRequest\x1a\".unheaded.v1.DictionaryGetResponse2\x8b\x01\n" +
	"\fWotanService\x12;\n" +
	"\x04Read\x12\x18.unheaded.v1.ReadRequest\x1a\x19.unheaded.v1.ReadResponse\x12>\n" +
	"\x05Write\x12\x19.unheaded.v1.WriteRequest\x1a\x1a.unheaded.v1.WriteResponse2\x91\x01\n" +
	"\x10AnamnesisService\x12A\n" +
	"\x05Query\x12\x17.unheaded.v1.EventQuery\x1a\x1f.unheaded.v1.EventQueryResponse\x12:\n" +
	"\x06Stream\x12\x1a.unheaded.v1.StreamRequest\x1a\x12.unheaded.v1.Event0\x012\xcd\x01\n" +
	"\vFlowService\x12=\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x1d.unheaded.v1.FlowListResponse\x12<\n" +
	"\bGetState\x12\x18.unheaded.v1.ReadRequest\x1a\x16.unheaded.v1.FlowState\x12A\n" +
	"\x06Inject\x12\x1a.unheaded.v1.InjectRequest\x1a\x1b.unheaded.v1.InjectResponseB'Z%unheaded/proto/unheaded/v1;unheadedv1b\x06proto3"

var (
	file_unheaded_v1_protocol_proto_rawDescOnce sync.Once
	file_unheaded_v1_protocol_proto_rawDescData []byte
)

func file_unheaded_v1_protocol_proto_rawDescGZIP() []byte {
	file_unheaded_v1_protocol_proto_rawDescOnce.Do(func() {
		file_unheaded_v1_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_unheaded_v1_protocol_proto_rawDesc), len(file_unheaded_v1_protocol_proto_rawDesc)))
	})
	return file_unheaded_v1_protocol_proto_rawDescData
}

var file_unheaded_v1_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_unheaded_v1_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_unheaded_v1_protocol_proto_goTypes = []any{
	(KingdomMode)(0),               // 0: unheaded.v1.KingdomMode
	(Event_EventType)(0),           // 1: unheaded.v1.Event.EventType
	(*MonadRegister)(nil),          // 2: unheaded.v1.MonadRegister
	(*EncodeRequest)(nil),          // 3: unheaded.v1.EncodeRequest
	(*EncodeResponse)(nil),         // 4: unheaded.v1.EncodeResponse
	(*DecodeRequest)(nil),          // 5: unheaded.v1.DecodeRequest
	(*DecodeResponse)(nil),         // 6: unheaded.v1.DecodeResponse
	(*DictionaryEntry)(nil),        // 7: unheaded.v1.DictionaryEntry
	(*Dictionary)(nil),             // 8: unheaded.v1.Dictionary
	(*DictionaryListRequest)(nil),  // 9: unheaded.v1.DictionaryListRequest
	(*DictionaryListResponse)(nil), // 10: unheaded.v1.DictionaryListResponse
	(*DictionaryGetRequest)(nil),   // 11: unheaded.v1.DictionaryGetRequest
	(*DictionaryGetResponse)(nil),  // 12: unheaded.v1.DictionaryGetResponse
	(*MemorySlot)(nil),             // 13: unheaded.v1.MemorySlot
	(*ReadRequest)(nil),            // 14: unheaded.v1.ReadRequest
	(*ReadResponse)(nil),           // 15: unheaded.v1.ReadResponse
	(*WriteRequest)(nil),           // 16: unheaded.v1.WriteRequest
	(*WriteResponse)(nil),          // 17: unheaded.v1.WriteResponse
	(*Event)(nil),                  // 18: unheaded.v1.Event
	(*EventQuery)(nil),             // 19: unheaded.v1.EventQuery
	(*EventQueryResponse)(nil),     // 20: unheaded.v1.EventQueryResponse
	(*StreamRequest)(nil),          // 21: unheaded.v1.StreamRequest
	(*FlowState)(nil),              // 22: unheaded.v1.FlowState
	(*FlowListResponse)(nil),       // 23: unheaded.v1.FlowListResponse
	(*InjectRequest)(nil),          // 24: unheaded.v1.InjectRequest
	(*InjectResponse)(nil),         // 25: unheaded.v1.InjectResponse
	nil,                            // 26: unheaded.v1.Event.MetadataEntry
	(*emptypb.Empty)(nil),          // 27: google.protobuf.Empty
}
var file_unheaded_v1_protocol_proto_depIdxs = []int32{
	0,  // 0: unheaded.v1.MonadRegister.kingdom_mode:type_name -> unheaded.v1.KingdomMode
	0,  // 1: unheaded.v1.EncodeRequest.kingdom_mode:type_name -> unheaded.v1.KingdomMode
	0,  // 2: unheaded.v1.DecodeResponse.kingdom_mode:type_name -> unheaded.v1.KingdomMode
	7,  // 3: unheaded.v1.Dictionary.entries:type_name -> unheaded.v1.DictionaryEntry
	8,  // 4: unheaded.v1.DictionaryListResponse.dictionaries:type_name -> unheaded.v1.Dictionary
	8,  // 5: unheaded.v1.DictionaryGetResponse.dictionary:type_name -> unheaded.v1.Dictionary
	13, // 6: unheaded.v1.ReadResponse.slot:type_name -> unheaded.v1.MemorySlot
	1,  // 7: unheaded.v1.Event.type:type_name -> unheaded.v1.Event.EventType
	26, // 8: unheaded.v1.Event.metadata:type_name -> unheaded.v1.Event.MetadataEntry
	1,  // 9: unheaded.v1.EventQuery.event_types:type_name -> unheaded.v1.Event.EventType
	18, // 10: unheaded.v1.EventQueryResponse.events:type_name -> unheaded.v1.Event
	1,  // 11: unheaded.v1.StreamRequest.event_types:type_name -> unheaded.v1.Event.EventType
	0,  // 12: unheaded.v1.FlowState.kingdom_mode:type_name -> unheaded.v1.KingdomMode
	22, // 13: unheaded.v1.FlowListResponse.flows:type_name -> unheaded.v1.FlowState
	0,  // 14: unheaded.v1.InjectRequest.kingdom_mode:type_name -> unheaded.v1.KingdomMode
	3,  // 15: unheaded.v1.MonadService.Encode:input_type -> unheaded.v1.EncodeRequest
	5,  // 16: unheaded.v1.MonadService.Decode:input_type -> unheaded.v1.DecodeRequest
	5,  // 17: unheaded.v1.MonadService.Validate:input_type -> unheaded.v1.DecodeRequest
	9,  // 18: unheaded.v1.SophiaService.List:input_type -> unheaded.v1.DictionaryListRequest
	11, // 19: unheaded.v1.SophiaService.Get:input_type -> unheaded.v1.DictionaryGetRequest
	14, // 20: unheaded.v1.WotanService.Read:input_type -> unheaded.v1.ReadRequest
	16, // 21: unheaded.v1.WotanService.Write:input_type -> unheaded.v1.WriteRequest
	19, // 22: unheaded.v1.AnamnesisService.Query:input_type -> unheaded.v1.EventQuery
	21, // 23: unheaded.v1.AnamnesisService.Stream:input_type -> unheaded.v1.StreamRequest
	27, // 24: unheaded.v1.FlowService.List:input_type -> google.protobuf.Empty
	14, // 25: unheaded.v1.FlowService.GetState:input_type -> unheaded.v1.ReadRequest
	24, // 26: unheaded.v1.FlowService.Inject:input_type -> unheaded.v1.InjectRequest
	4,  // 27: unheaded.v1.MonadService.Encode:output_type -> unheaded.v1.EncodeResponse
	6,  // 28: unheaded.v1.MonadService.Decode:output_type -> unheaded.v1.DecodeResponse
	6,  // 29: unheaded.v1.MonadService.Validate:output_type -> unheaded.v1.DecodeResponse
	10, // 30: unheaded.v1.SophiaService.List:output_type -> unheaded.v1.DictionaryListResponse
	12, // 31: unheaded.v1.SophiaService.Get:output_type -> unheaded.v1.DictionaryGetResponse
	15, // 32: unheaded.v1.WotanService.Read:output_type -> unheaded.v1.ReadResponse
	17, // 33: unheaded.v1.WotanService.Write:output_type -> unheaded.v1.WriteResponse
	20, // 34: unheaded.v1.AnamnesisService.Query:output_type -> unheaded.v1.EventQueryResponse
	18, // 35: unheaded.v1.AnamnesisService.Stream:output_type -> unheaded.v1.Event
	23, // 36: unheaded.v1.FlowService.List:output_type -> unheaded.v1.FlowListResponse
	22, // 37: unheaded.v1.FlowService.GetState:output_type -> unheaded.v1.FlowState
	25, // 38: unheaded.v1.FlowService.Inject:output_type -> unheaded.v1.InjectResponse
	27, // [27:39] is the sub-list for method output_type
	15, // [15:27] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_unheaded_v1_protocol_proto_init() }
func file_unheaded_v1_protocol_proto_init() {
	if File_unheaded_v1_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_unheaded_v1_protocol_proto_rawDesc), len(file_unheaded_v1_protocol_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_unheaded_v1_protocol_proto_goTypes,
		DependencyIndexes: file_unheaded_v1_protocol_proto_depIdxs,
		EnumInfos:         file_unheaded_v1_protocol_proto_enumTypes,
		MessageInfos:      file_unheaded_v1_protocol_proto_msgTypes,
	}.Build()
	File_unheaded_v1_protocol_proto = out.File
	file_unheaded_v1_protocol_proto_goTypes = nil
	file_unheaded_v1_protocol_proto_depIdxs = nil
}
