# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2024-2026 Stevie Bellis.

apiVersion: v1
kind: Service
metadata:
  name: cuirass
  namespace: unheaded
  labels:
    app.kubernetes.io/name: cuirass
    kingdom.armor: cuirass
spec:
  selector:
    app.kubernetes.io/name: cuirass
  ports:
    - { name: http, port: 19006, targetPort: 19006 }
