// SPDX-License-Identifier: BUSL-1.1
// Copyright (c) 2024-2026 Steven Bellis. All rights reserved.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: chat.proto

package chatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatStream_StreamMessages_FullMethodName = "/chat.ChatStream/StreamMessages"
	ChatStream_Ping_FullMethodName           = "/chat.ChatStream/Ping"
)

// ChatStreamClient is the client API for ChatStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChatStream service provides live message streaming for rooms
type ChatStreamClient interface {
	// StreamMessages subscribes to live messages from a room
	StreamMessages(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageEvent], error)
	// Ping keeps the connection alive
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error)
}

type chatStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewChatStreamClient(cc grpc.ClientConnInterface) ChatStreamClient {
	return &chatStreamClient{cc}
}

func (c *chatStreamClient) StreamMessages(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatStream_ServiceDesc.Streams[0], ChatStream_StreamMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, MessageEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatStream_StreamMessagesClient = grpc.ServerStreamingClient[MessageEvent]

func (c *chatStreamClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PongResponse)
	err := c.cc.Invoke(ctx, ChatStream_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatStreamServer is the server API for ChatStream service.
// All implementations must embed UnimplementedChatStreamServer
// for forward compatibility.
//
// ChatStream service provides live message streaming for rooms
type ChatStreamServer interface {
	// StreamMessages subscribes to live messages from a room
	StreamMessages(*StreamRequest, grpc.ServerStreamingServer[MessageEvent]) error
	// Ping keeps the connection alive
	Ping(context.Context, *PingRequest) (*PongResponse, error)
	mustEmbedUnimplementedChatStreamServer()
}

// UnimplementedChatStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatStreamServer struct{}

func (UnimplementedChatStreamServer) StreamMessages(*StreamRequest, grpc.ServerStreamingServer[MessageEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamMessages not implemented")
}
func (UnimplementedChatStreamServer) Ping(context.Context, *PingRequest) (*PongResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedChatStreamServer) mustEmbedUnimplementedChatStreamServer() {}
func (UnimplementedChatStreamServer) testEmbeddedByValue()                    {}

// UnsafeChatStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatStreamServer will
// result in compilation errors.
type UnsafeChatStreamServer interface {
	mustEmbedUnimplementedChatStreamServer()
}

func RegisterChatStreamServer(s grpc.ServiceRegistrar, srv ChatStreamServer) {
	// If the following call panics, it indicates UnimplementedChatStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatStream_ServiceDesc, srv)
}

func _ChatStream_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatStreamServer).StreamMessages(m, &grpc.GenericServerStream[StreamRequest, MessageEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatStream_StreamMessagesServer = grpc.ServerStreamingServer[MessageEvent]

func _ChatStream_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatStreamServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatStream_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatStreamServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatStream_ServiceDesc is the grpc.ServiceDesc for ChatStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatStream",
	HandlerType: (*ChatStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ChatStream_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _ChatStream_StreamMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat.proto",
}
