// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2025-2026 Steven Bellis. All rights reserved.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: replication.proto

package chatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WotanReplication_CatchUp_FullMethodName          = "/wotan.WotanReplication/CatchUp"
	WotanReplication_ReplicationPing_FullMethodName  = "/wotan.WotanReplication/ReplicationPing"
	WotanReplication_TransferSnapshot_FullMethodName = "/wotan.WotanReplication/TransferSnapshot"
)

// WotanReplicationClient is the client API for WotanReplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WotanReplication handles WAL-based replication between primary and standby.
type WotanReplicationClient interface {
	// CatchUp: standby requests WAL entries from a specific sequence.
	// Primary streams all entries since that sequence.
	CatchUp(ctx context.Context, in *CatchUpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WALEntry], error)
	// ReplicationPing: health/status exchange between nodes.
	ReplicationPing(ctx context.Context, in *ReplicationPingRequest, opts ...grpc.CallOption) (*ReplicationPongResponse, error)
	// TransferSnapshot: full state transfer for initial sync or large gaps.
	TransferSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error)
}

type wotanReplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewWotanReplicationClient(cc grpc.ClientConnInterface) WotanReplicationClient {
	return &wotanReplicationClient{cc}
}

func (c *wotanReplicationClient) CatchUp(ctx context.Context, in *CatchUpRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WALEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WotanReplication_ServiceDesc.Streams[0], WotanReplication_CatchUp_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CatchUpRequest, WALEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WotanReplication_CatchUpClient = grpc.ServerStreamingClient[WALEntry]

func (c *wotanReplicationClient) ReplicationPing(ctx context.Context, in *ReplicationPingRequest, opts ...grpc.CallOption) (*ReplicationPongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicationPongResponse)
	err := c.cc.Invoke(ctx, WotanReplication_ReplicationPing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wotanReplicationClient) TransferSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WotanReplication_ServiceDesc.Streams[1], WotanReplication_TransferSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotRequest, SnapshotChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WotanReplication_TransferSnapshotClient = grpc.ServerStreamingClient[SnapshotChunk]

// WotanReplicationServer is the server API for WotanReplication service.
// All implementations must embed UnimplementedWotanReplicationServer
// for forward compatibility.
//
// WotanReplication handles WAL-based replication between primary and standby.
type WotanReplicationServer interface {
	// CatchUp: standby requests WAL entries from a specific sequence.
	// Primary streams all entries since that sequence.
	CatchUp(*CatchUpRequest, grpc.ServerStreamingServer[WALEntry]) error
	// ReplicationPing: health/status exchange between nodes.
	ReplicationPing(context.Context, *ReplicationPingRequest) (*ReplicationPongResponse, error)
	// TransferSnapshot: full state transfer for initial sync or large gaps.
	TransferSnapshot(*SnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error
	mustEmbedUnimplementedWotanReplicationServer()
}

// UnimplementedWotanReplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWotanReplicationServer struct{}

func (UnimplementedWotanReplicationServer) CatchUp(*CatchUpRequest, grpc.ServerStreamingServer[WALEntry]) error {
	return status.Error(codes.Unimplemented, "method CatchUp not implemented")
}
func (UnimplementedWotanReplicationServer) ReplicationPing(context.Context, *ReplicationPingRequest) (*ReplicationPongResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicationPing not implemented")
}
func (UnimplementedWotanReplicationServer) TransferSnapshot(*SnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error {
	return status.Error(codes.Unimplemented, "method TransferSnapshot not implemented")
}
func (UnimplementedWotanReplicationServer) mustEmbedUnimplementedWotanReplicationServer() {}
func (UnimplementedWotanReplicationServer) testEmbeddedByValue()                          {}

// UnsafeWotanReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WotanReplicationServer will
// result in compilation errors.
type UnsafeWotanReplicationServer interface {
	mustEmbedUnimplementedWotanReplicationServer()
}

func RegisterWotanReplicationServer(s grpc.ServiceRegistrar, srv WotanReplicationServer) {
	// If the following call panics, it indicates UnimplementedWotanReplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WotanReplication_ServiceDesc, srv)
}

func _WotanReplication_CatchUp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CatchUpRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WotanReplicationServer).CatchUp(m, &grpc.GenericServerStream[CatchUpRequest, WALEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WotanReplication_CatchUpServer = grpc.ServerStreamingServer[WALEntry]

func _WotanReplication_ReplicationPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WotanReplicationServer).ReplicationPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WotanReplication_ReplicationPing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WotanReplicationServer).ReplicationPing(ctx, req.(*ReplicationPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WotanReplication_TransferSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WotanReplicationServer).TransferSnapshot(m, &grpc.GenericServerStream[SnapshotRequest, SnapshotChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WotanReplication_TransferSnapshotServer = grpc.ServerStreamingServer[SnapshotChunk]

// WotanReplication_ServiceDesc is the grpc.ServiceDesc for WotanReplication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WotanReplication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wotan.WotanReplication",
	HandlerType: (*WotanReplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReplicationPing",
			Handler:    _WotanReplication_ReplicationPing_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CatchUp",
			Handler:       _WotanReplication_CatchUp_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TransferSnapshot",
			Handler:       _WotanReplication_TransferSnapshot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "replication.proto",
}
