// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2024-2026 Steven Bellis. All rights reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: topic.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicEventType int32

const (
	TopicEventType_TOPIC_MESSAGE_PUBLISHED  TopicEventType = 0
	TopicEventType_TOPIC_MESSAGE_DELETED    TopicEventType = 1
	TopicEventType_TOPIC_SUBSCRIPTION_ADDED TopicEventType = 2
)

// Enum value maps for TopicEventType.
var (
	TopicEventType_name = map[int32]string{
		0: "TOPIC_MESSAGE_PUBLISHED",
		1: "TOPIC_MESSAGE_DELETED",
		2: "TOPIC_SUBSCRIPTION_ADDED",
	}
	TopicEventType_value = map[string]int32{
		"TOPIC_MESSAGE_PUBLISHED":  0,
		"TOPIC_MESSAGE_DELETED":    1,
		"TOPIC_SUBSCRIPTION_ADDED": 2,
	}
)

func (x TopicEventType) Enum() *TopicEventType {
	p := new(TopicEventType)
	*p = x
	return p
}

func (x TopicEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopicEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_topic_proto_enumTypes[0].Descriptor()
}

func (TopicEventType) Type() protoreflect.EnumType {
	return &file_topic_proto_enumTypes[0]
}

func (x TopicEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopicEventType.Descriptor instead.
func (TopicEventType) EnumDescriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{0}
}

type TopicStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicPattern  string                 `protobuf:"bytes,1,opt,name=topic_pattern,json=topicPattern,proto3" json:"topic_pattern,omitempty"`
	SubscriberId  string                 `protobuf:"bytes,2,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SinceSeq      int64                  `protobuf:"varint,4,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	NodeId        string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicStreamRequest) Reset() {
	*x = TopicStreamRequest{}
	mi := &file_topic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicStreamRequest) ProtoMessage() {}

func (x *TopicStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicStreamRequest.ProtoReflect.Descriptor instead.
func (*TopicStreamRequest) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{0}
}

func (x *TopicStreamRequest) GetTopicPattern() string {
	if x != nil {
		return x.TopicPattern
	}
	return ""
}

func (x *TopicStreamRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *TopicStreamRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *TopicStreamRequest) GetSinceSeq() int64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

func (x *TopicStreamRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TopicStreamRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TopicEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Seq           int64                  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Type          TopicEventType         `protobuf:"varint,7,opt,name=type,proto3,enum=chat.TopicEventType" json:"type,omitempty"`
	NodeId        string                 `protobuf:"bytes,8,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicEvent) Reset() {
	*x = TopicEvent{}
	mi := &file_topic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicEvent) ProtoMessage() {}

func (x *TopicEvent) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicEvent.ProtoReflect.Descriptor instead.
func (*TopicEvent) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{1}
}

func (x *TopicEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *TopicEvent) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TopicEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *TopicEvent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TopicEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TopicEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TopicEvent) GetType() TopicEventType {
	if x != nil {
		return x.Type
	}
	return TopicEventType_TOPIC_MESSAGE_PUBLISHED
}

func (x *TopicEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type TopicPublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicPublishRequest) Reset() {
	*x = TopicPublishRequest{}
	mi := &file_topic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPublishRequest) ProtoMessage() {}

func (x *TopicPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPublishRequest.ProtoReflect.Descriptor instead.
func (*TopicPublishRequest) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{2}
}

func (x *TopicPublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TopicPublishRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *TopicPublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TopicPublishRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TopicPublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicPublishResponse) Reset() {
	*x = TopicPublishResponse{}
	mi := &file_topic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicPublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPublishResponse) ProtoMessage() {}

func (x *TopicPublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPublishResponse.ProtoReflect.Descriptor instead.
func (*TopicPublishResponse) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{3}
}

func (x *TopicPublishResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *TopicPublishResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TopicPublishResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TopicPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicPingRequest) Reset() {
	*x = TopicPingRequest{}
	mi := &file_topic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPingRequest) ProtoMessage() {}

func (x *TopicPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPingRequest.ProtoReflect.Descriptor instead.
func (*TopicPingRequest) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{4}
}

func (x *TopicPingRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TopicPingRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type TopicPongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ActiveStreams int64                  `protobuf:"varint,3,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	TotalTopics   int64                  `protobuf:"varint,4,opt,name=total_topics,json=totalTopics,proto3" json:"total_topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicPongResponse) Reset() {
	*x = TopicPongResponse{}
	mi := &file_topic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicPongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPongResponse) ProtoMessage() {}

func (x *TopicPongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPongResponse.ProtoReflect.Descriptor instead.
func (*TopicPongResponse) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{5}
}

func (x *TopicPongResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TopicPongResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TopicPongResponse) GetActiveStreams() int64 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

func (x *TopicPongResponse) GetTotalTopics() int64 {
	if x != nil {
		return x.TotalTopics
	}
	return 0
}

var File_topic_proto protoreflect.FileDescriptor

const file_topic_proto_rawDesc = "" +
	"\n" +
	"\vtopic.proto\x12\x04chat\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x02\n" +
	"\x12TopicStreamRequest\x12#\n" +
	"\rtopic_pattern\x18\x01 \x01(\tR\ftopicPattern\x12#\n" +
	"\rsubscriber_id\x18\x02 \x01(\tR\fsubscriberId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1b\n" +
	"\tsince_seq\x18\x04 \x01(\x03R\bsinceSeq\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12B\n" +
	"\bmetadata\x18\x06 \x03(\v2&.chat.TopicStreamRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x02\n" +
	"\n" +
	"TopicEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x03R\x03seq\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12(\n" +
	"\x04type\x18\a \x01(\x0e2\x14.chat.TopicEventTypeR\x04type\x12\x17\n" +
	"\anode_id\x18\b \x01(\tR\x06nodeId\"\xe4\x01\n" +
	"\x13TopicPublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12C\n" +
	"\bmetadata\x18\x04 \x03(\v2'.chat.TopicPublishRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x14TopicPublishResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"e\n" +
	"\x10TopicPingRequest\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"\xaf\x01\n" +
	"\x11TopicPongResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0eactive_streams\x18\x03 \x01(\x03R\ractiveStreams\x12!\n" +
	"\ftotal_topics\x18\x04 \x01(\x03R\vtotalTopics*f\n" +
	"\x0eTopicEventType\x12\x1b\n" +
	"\x17TOPIC_MESSAGE_PUBLISHED\x10\x00\x12\x19\n" +
	"\x15TOPIC_MESSAGE_DELETED\x10\x01\x12\x1c\n" +
	"\x18TOPIC_SUBSCRIPTION_ADDED\x10\x022\xd0\x01\n" +
	"\vTopicStream\x12<\n" +
	"\fStreamTopics\x12\x18.chat.TopicStreamRequest\x1a\x10.chat.TopicEvent0\x01\x12E\n" +
	"\fPublishTopic\x12\x19.chat.TopicPublishRequest\x1a\x1a.chat.TopicPublishResponse\x12<\n" +
	"\tTopicPing\x12\x16.chat.TopicPingRequest\x1a\x17.chat.TopicPongResponseB'Z%github.com/unheaded/chat/proto;chatpbb\x06proto3"

var (
	file_topic_proto_rawDescOnce sync.Once
	file_topic_proto_rawDescData []byte
)

func file_topic_proto_rawDescGZIP() []byte {
	file_topic_proto_rawDescOnce.Do(func() {
		file_topic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topic_proto_rawDesc), len(file_topic_proto_rawDesc)))
	})
	return file_topic_proto_rawDescData
}

var file_topic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_topic_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_topic_proto_goTypes = []any{
	(TopicEventType)(0),           // 0: chat.TopicEventType
	(*TopicStreamRequest)(nil),    // 1: chat.TopicStreamRequest
	(*TopicEvent)(nil),            // 2: chat.TopicEvent
	(*TopicPublishRequest)(nil),   // 3: chat.TopicPublishRequest
	(*TopicPublishResponse)(nil),  // 4: chat.TopicPublishResponse
	(*TopicPingRequest)(nil),      // 5: chat.TopicPingRequest
	(*TopicPongResponse)(nil),     // 6: chat.TopicPongResponse
	nil,                           // 7: chat.TopicStreamRequest.MetadataEntry
	nil,                           // 8: chat.TopicPublishRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_topic_proto_depIdxs = []int32{
	7,  // 0: chat.TopicStreamRequest.metadata:type_name -> chat.TopicStreamRequest.MetadataEntry
	9,  // 1: chat.TopicEvent.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: chat.TopicEvent.type:type_name -> chat.TopicEventType
	8,  // 3: chat.TopicPublishRequest.metadata:type_name -> chat.TopicPublishRequest.MetadataEntry
	9,  // 4: chat.TopicPublishResponse.created_at:type_name -> google.protobuf.Timestamp
	9,  // 5: chat.TopicPingRequest.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 6: chat.TopicPongResponse.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 7: chat.TopicStream.StreamTopics:input_type -> chat.TopicStreamRequest
	3,  // 8: chat.TopicStream.PublishTopic:input_type -> chat.TopicPublishRequest
	5,  // 9: chat.TopicStream.TopicPing:input_type -> chat.TopicPingRequest
	2,  // 10: chat.TopicStream.StreamTopics:output_type -> chat.TopicEvent
	4,  // 11: chat.TopicStream.PublishTopic:output_type -> chat.TopicPublishResponse
	6,  // 12: chat.TopicStream.TopicPing:output_type -> chat.TopicPongResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_topic_proto_init() }
func file_topic_proto_init() {
	if File_topic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topic_proto_rawDesc), len(file_topic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_topic_proto_goTypes,
		DependencyIndexes: file_topic_proto_depIdxs,
		EnumInfos:         file_topic_proto_enumTypes,
		MessageInfos:      file_topic_proto_msgTypes,
	}.Build()
	File_topic_proto = out.File
	file_topic_proto_goTypes = nil
	file_topic_proto_depIdxs = nil
}
