// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2024-2026 Stevie Bellis. All rights reserved.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: topic.proto

package chatpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TopicStream_StreamTopics_FullMethodName = "/chat.TopicStream/StreamTopics"
	TopicStream_PublishTopic_FullMethodName = "/chat.TopicStream/PublishTopic"
	TopicStream_TopicPing_FullMethodName    = "/chat.TopicStream/TopicPing"
)

// TopicStreamClient is the client API for TopicStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TopicStreamClient interface {
	// Server-side streaming: subscribe to topics matching a pattern
	StreamTopics(ctx context.Context, in *TopicStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopicEvent], error)
	// Publish a message to a topic
	PublishTopic(ctx context.Context, in *TopicPublishRequest, opts ...grpc.CallOption) (*TopicPublishResponse, error)
	// Health/keepalive
	TopicPing(ctx context.Context, in *TopicPingRequest, opts ...grpc.CallOption) (*TopicPongResponse, error)
}

type topicStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewTopicStreamClient(cc grpc.ClientConnInterface) TopicStreamClient {
	return &topicStreamClient{cc}
}

func (c *topicStreamClient) StreamTopics(ctx context.Context, in *TopicStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopicEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TopicStream_ServiceDesc.Streams[0], TopicStream_StreamTopics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TopicStreamRequest, TopicEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopicStream_StreamTopicsClient = grpc.ServerStreamingClient[TopicEvent]

func (c *topicStreamClient) PublishTopic(ctx context.Context, in *TopicPublishRequest, opts ...grpc.CallOption) (*TopicPublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicPublishResponse)
	err := c.cc.Invoke(ctx, TopicStream_PublishTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicStreamClient) TopicPing(ctx context.Context, in *TopicPingRequest, opts ...grpc.CallOption) (*TopicPongResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopicPongResponse)
	err := c.cc.Invoke(ctx, TopicStream_TopicPing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopicStreamServer is the server API for TopicStream service.
// All implementations must embed UnimplementedTopicStreamServer
// for forward compatibility.
type TopicStreamServer interface {
	// Server-side streaming: subscribe to topics matching a pattern
	StreamTopics(*TopicStreamRequest, grpc.ServerStreamingServer[TopicEvent]) error
	// Publish a message to a topic
	PublishTopic(context.Context, *TopicPublishRequest) (*TopicPublishResponse, error)
	// Health/keepalive
	TopicPing(context.Context, *TopicPingRequest) (*TopicPongResponse, error)
	mustEmbedUnimplementedTopicStreamServer()
}

// UnimplementedTopicStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTopicStreamServer struct{}

func (UnimplementedTopicStreamServer) StreamTopics(*TopicStreamRequest, grpc.ServerStreamingServer[TopicEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamTopics not implemented")
}
func (UnimplementedTopicStreamServer) PublishTopic(context.Context, *TopicPublishRequest) (*TopicPublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishTopic not implemented")
}
func (UnimplementedTopicStreamServer) TopicPing(context.Context, *TopicPingRequest) (*TopicPongResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TopicPing not implemented")
}
func (UnimplementedTopicStreamServer) mustEmbedUnimplementedTopicStreamServer() {}
func (UnimplementedTopicStreamServer) testEmbeddedByValue()                     {}

// UnsafeTopicStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TopicStreamServer will
// result in compilation errors.
type UnsafeTopicStreamServer interface {
	mustEmbedUnimplementedTopicStreamServer()
}

func RegisterTopicStreamServer(s grpc.ServiceRegistrar, srv TopicStreamServer) {
	// If the following call panics, it indicates UnimplementedTopicStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TopicStream_ServiceDesc, srv)
}

func _TopicStream_StreamTopics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TopicStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TopicStreamServer).StreamTopics(m, &grpc.GenericServerStream[TopicStreamRequest, TopicEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopicStream_StreamTopicsServer = grpc.ServerStreamingServer[TopicEvent]

func _TopicStream_PublishTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicPublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicStreamServer).PublishTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopicStream_PublishTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicStreamServer).PublishTopic(ctx, req.(*TopicPublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicStream_TopicPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicStreamServer).TopicPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopicStream_TopicPing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicStreamServer).TopicPing(ctx, req.(*TopicPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TopicStream_ServiceDesc is the grpc.ServiceDesc for TopicStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TopicStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.TopicStream",
	HandlerType: (*TopicStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishTopic",
			Handler:    _TopicStream_PublishTopic_Handler,
		},
		{
			MethodName: "TopicPing",
			Handler:    _TopicStream_TopicPing_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTopics",
			Handler:       _TopicStream_StreamTopics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "topic.proto",
}
