# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2024-2026 Stevie Bellis.

apiVersion: v1
kind: Service
metadata:
  name: timeguru
  namespace: unheaded
  labels:
    app.kubernetes.io/name: timeguru
    kingdom.armor: oracle
spec:
  selector:
    app.kubernetes.io/name: timeguru
  ports:
    - { name: http, port: 19000, targetPort: 19000 }
