[package]
name        = "shield-ebpf"
description = "Shield boundary enforcement layer — XDP ingress (BIRTH) and TC egress (DEATH)"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
authors.workspace    = true

[dependencies]
aya-ebpf.workspace     = true
aya-log-ebpf.workspace = true
monad-common.workspace = true
