[package]
name        = "yaldabaoth-ebpf"
description = "Unheaded Protocol chaos injection TC egress program — the Demiurge corrupts"
version.workspace   = true
edition.workspace   = true
publish.workspace   = true

[[bin]]
name = "yaldabaoth-ebpf"
path = "src/main.rs"

[dependencies]
aya-ebpf.workspace     = true
aya-log-ebpf.workspace = true
monad-common.workspace = true
