apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unheaded-armory
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/unheaded/unheaded.git
    targetRevision: HEAD
    path: deploy/k8s/armory
  destination:
    server: https://kubernetes.default.svc
    namespace: unheaded-armory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
