apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unheaded-gnostic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/unheaded/unheaded.git
    targetRevision: HEAD
    path: deploy/k8s/gnostic
  destination:
    server: https://kubernetes.default.svc
    namespace: unheaded-gnostic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
