apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: unheaded
  namespace: argocd
spec:
  description: "Unheaded Kingdom infrastructure"
  sourceRepos:
  - "https://github.com/unheaded/unheaded.git"
  destinations:
  - namespace: "unheaded-*"
    server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: "rbac.authorization.k8s.io"
    kind: ClusterRole
  - group: "rbac.authorization.k8s.io"
    kind: ClusterRoleBinding
  namespaceResourceBlacklist:
  - group: ""
    kind: Secret
  orphanedResources:
    warn: true
