# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2024-2026 Stevie Bellis.

apiVersion: v1
kind: Service
metadata:
  name: monad
  namespace: unheaded
  labels:
    app.kubernetes.io/name: monad
    kingdom.armor: monad
spec:
  selector:
    app.kubernetes.io/name: monad
  ports:
    - { name: http, port: 19004, targetPort: 19004 }
