# TYPE  DATABASE  USER      ADDRESS       METHOD
local   all       postgres                peer
local   all       unheaded                scram-sha-256
host    all       unheaded  172.0.0.0/8   scram-sha-256
host    all       unheaded  10.0.0.0/8    scram-sha-256
host    all       all       0.0.0.0/0     reject
