[package]
name = "monad-mbc-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
monad-mbc = { path = ".." }
monad-common = { path = "../../../ebpf/monad-common" }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "fuzz_mbc_decode"
path = "fuzz_targets/fuzz_mbc_decode.rs"
doc = false

[[bin]]
name = "fuzz_mbc_execute"
path = "fuzz_targets/fuzz_mbc_execute.rs"
doc = false

[[bin]]
name = "fuzz_mbc_roundtrip"
path = "fuzz_targets/fuzz_mbc_roundtrip.rs"
doc = false
