# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2024-2026 Stevie Bellis.

apiVersion: v1
kind: Service
metadata:
  name: captain
  namespace: unheaded
  labels:
    app.kubernetes.io/name: captain
    kingdom.armor: commander
spec:
  selector:
    app.kubernetes.io/name: captain
  ports:
    - { name: http, port: 19002, targetPort: 19002 }
