# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2024-2026 Stevie Bellis.

apiVersion: v1
kind: ConfigMap
metadata:
  name: suricata-config
  namespace: unheaded
data:
  suricata.yaml: |
    vars:
      address-groups:
        HOME_NET: "[10.0.0.0/8, fd00:dead:beef::/48]"
        EXTERNAL_NET: "!$HOME_NET"
    logging:
      default-log-level: notice
      outputs:
        - console:
            enabled: yes
    af-packet:
      - interface: default
        cluster-id: 99
        cluster-type: cluster_flow
        defrag: yes
    outputs:
      - eve-log:
          enabled: yes
          filetype: regular
          filename: /var/log/suricata/eve.json
          types:
            - alert
            - dns
            - http
            - flow
