// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2024-2026 Steven Bellis. All rights reserved.

// Package campaigns implements the 6 Lich offensive security campaigns.
package campaigns

import (
	"context"
	"fmt"
	"strings"
	"time"
)

// Config holds connection details for the Unheaded stack.
type Config struct {
	GatewayAddr   string
	WotanAddr     string
	DashboardAddr string
}

// Finding represents a security issue discovered during a campaign.
type Finding struct {
	ID          string `json:"id"`
	Severity    string `json:"severity"` // critical, high, medium, low
	Title       string `json:"title"`
	Description string `json:"description"`
	Remediation string `json:"remediation"`
	Endpoint    string `json:"endpoint,omitempty"`
}

// CampaignResult holds the outcome of a single campaign run.
type CampaignResult struct {
	Campaign    string        `json:"campaign"`
	Description string        `json:"description"`
	StartTime   time.Time     `json:"start_time"`
	Duration    time.Duration `json:"duration"`
	TestsRun    int           `json:"tests_run"`
	TestsPassed int           `json:"tests_passed"`
	Findings    []Finding     `json:"findings"`
	Error       string        `json:"error,omitempty"`
}

// Campaign is the interface all Lich campaigns implement.
type Campaign interface {
	Name() string
	Description() string
	Run(ctx context.Context, cfg Config) CampaignResult
}

// Runner manages campaign execution.
type Runner struct {
	cfg       Config
	campaigns map[string]Campaign
}

// NewRunner creates a runner with all 6 campaigns registered.
func NewRunner(cfg Config) *Runner {
	r := &Runner{
		cfg:       cfg,
		campaigns: make(map[string]Campaign),
	}
	r.campaigns["d1"] = &D1AuthBypass{}
	r.campaigns["d2"] = &D2Injection{}
	r.campaigns["d3"] = &D3TransportSecurity{}
	r.campaigns["d4"] = &D4Secrets{}
	r.campaigns["d5"] = &D5PrivilegeEscalation{}
	r.campaigns["d6"] = &D6DenialOfService{}
	return r
}

// Run executes the selected campaigns and returns results.
func (r *Runner) Run(ctx context.Context, selected []string) []CampaignResult {
	var results []CampaignResult
	for _, name := range selected {
		c, ok := r.campaigns[name]
		if !ok {
			results = append(results, CampaignResult{
				Campaign: name,
				Error:    fmt.Sprintf("unknown campaign: %s", name),
			})
			continue
		}
		result := c.Run(ctx, r.cfg)
		results = append(results, result)
	}
	return results
}

// GenerateReport produces a Markdown security audit report from campaign results.
func GenerateReport(results []CampaignResult) string {
	var b strings.Builder

	b.WriteString("# Lich Security Audit Report\n\n")
	b.WriteString(fmt.Sprintf("**Generated:** %s\n\n", time.Now().UTC().Format(time.RFC3339)))

	// Executive summary.
	totalTests := 0
	totalPassed := 0
	totalFindings := 0
	for _, r := range results {
		totalTests += r.TestsRun
		totalPassed += r.TestsPassed
		totalFindings += len(r.Findings)
	}

	b.WriteString("## Executive Summary\n\n")
	b.WriteString(fmt.Sprintf("- **Campaigns run:** %d\n", len(results)))
	b.WriteString(fmt.Sprintf("- **Total tests:** %d\n", totalTests))
	b.WriteString(fmt.Sprintf("- **Tests passed:** %d\n", totalPassed))
	b.WriteString(fmt.Sprintf("- **Total findings:** %d\n\n", totalFindings))

	// Campaign results.
	b.WriteString("## Campaign Results\n\n")
	b.WriteString("| Campaign | Status | Tests | Passed | Findings | Duration |\n")
	b.WriteString("|----------|--------|-------|--------|----------|----------|\n")
	for _, r := range results {
		status := "PASS"
		if len(r.Findings) > 0 {
			status = "FAIL"
		}
		if r.Error != "" {
			status = "ERROR"
		}
		b.WriteString(fmt.Sprintf("| %s | %s | %d | %d | %d | %s |\n",
			r.Campaign, status, r.TestsRun, r.TestsPassed, len(r.Findings),
			r.Duration.Round(time.Millisecond)))
	}
	b.WriteString("\n")

	// Detailed findings.
	if totalFindings > 0 {
		b.WriteString("## Detailed Findings\n\n")
		for _, r := range results {
			for _, f := range r.Findings {
				b.WriteString(fmt.Sprintf("### %s — %s\n\n", f.ID, f.Title))
				b.WriteString(fmt.Sprintf("- **Severity:** %s\n", f.Severity))
				b.WriteString(fmt.Sprintf("- **Campaign:** %s\n", r.Campaign))
				if f.Endpoint != "" {
					b.WriteString(fmt.Sprintf("- **Endpoint:** %s\n", f.Endpoint))
				}
				b.WriteString(fmt.Sprintf("- **Description:** %s\n", f.Description))
				b.WriteString(fmt.Sprintf("- **Remediation:** %s\n\n", f.Remediation))
			}
		}
	} else {
		b.WriteString("## Findings\n\nNo security findings. All campaigns passed.\n\n")
	}

	b.WriteString("---\n\n")
	b.WriteString("*Report generated by Lich Security Test Suite*\n")

	return b.String()
}
