# SPDX-License-Identifier: GPL-2.0
#
# arch/mbc/Makefile - Top-level Makefile for MBC (Monad Bytecode) architecture
#
# MBC is the ISA of the Unheaded Protocol Computer (UPC).
# This is a skeleton for the Linux kernel port (Week 1).
#

KBUILD_CFLAGS	+= -DCONFIG_MBC

core-y		+= arch/mbc/kernel/
