#!/bin/bash
set -euo pipefail
echo "=== Observability Stack Verification ==="
echo ""
echo "1. Prometheus..."
kubectl -n unheaded-system get pods -l app.kubernetes.io/name=prometheus && echo "  UP" || echo "  DOWN"
echo ""
echo "2. Grafana..."
kubectl -n unheaded-system get pods -l app.kubernetes.io/name=grafana && echo "  UP" || echo "  DOWN"
echo ""
echo "3. Alertmanager..."
kubectl -n unheaded-system get pods -l app.kubernetes.io/name=alertmanager && echo "  UP" || echo "  DOWN"
echo ""
echo "4. OTel Collector..."
kubectl -n unheaded-system get pods -l app.kubernetes.io/name=opentelemetry-collector && echo "  UP" || echo "  DOWN"
echo ""
echo "5. ServiceMonitors..."
kubectl get servicemonitors -A 2>/dev/null | grep unheaded || echo "  None found"
echo ""
echo "6. PrometheusRules..."
kubectl get prometheusrules -A 2>/dev/null | grep unheaded || echo "  None found"
echo ""
echo "=== Verification complete ==="
