# Patch overlay — adds CSI volume mount to cuirass-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuirass
  namespace: unheaded-armory
spec:
  template:
    spec:
      containers:
      - name: cuirass
        volumeMounts:
        - name: vault-secrets
          mountPath: "/mnt/secrets"
          readOnly: true
        env:
        - name: API_BIND_ADDR
          valueFrom:
            secretKeyRef:
              name: cuirass-config
              key: API_BIND_ADDR
        - name: GRPC_BIND_ADDR
          valueFrom:
            secretKeyRef:
              name: cuirass-config
              key: GRPC_BIND_ADDR
      volumes:
      - name: vault-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "cuirass-vault-secrets"
