! FRR IS-IS + Segment Routing MPLS — host-b (Outpost)
! SPDX-License-Identifier: MIT
frr version 10.0
hostname unheaded-outpost
log syslog informational
service integrated-vtysh-config
!
mpls enable
!
interface lo
 ip address 10.20.255.2/32
 ipv6 address fd00:dead:beef:ff::2/128
 isis enable isis-unheaded
 isis circuit-type level-2-only
 isis passive
!
interface wg0
 ip address 10.20.255.2/30
 ipv6 address fd00:dead:beef::2/48
 isis enable isis-unheaded
 isis circuit-type level-2-only
 isis hello-interval 3
 isis holddown 12
 isis ipv6 enable
 isis metric 10
 mpls enable
 isis bfd
!
interface br-unheaded
 ip address 10.20.0.253/16
 ipv6 address fd00:dead:beef:2::1/64
 isis enable isis-unheaded
 isis circuit-type level-2-only
 isis passive
 isis metric 1
!
router isis isis-unheaded
 net 49.0001.1020.0255.0002.00
 is-type level-2-only
 metric-style wide
 redistribute ipv6 connected
 redistribute ipv6 static
 !
 segment-routing on
 segment-routing global-block 16000 23999
 segment-routing local-block 15000 15999
 ! Prefix-SID for host-b loopback (absolute label 16002)
 segment-routing prefix fd00:dead:beef:ff::2/128 index 2
 !
 maximum-paths 4
!
bfd
 peer fd00:dead:beef::1 interface wg0
  receive-interval 300
  transmit-interval 300
  detect-multiplier 3
 !
!
end
