// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2024-2026 Stevie Bellis. All rights reserved.

package collect

import (
	"bytes"
	"errors"
	"fmt"
	"sort"
	"strconv"

	"gopkg.in/yaml.v3"

	"unheaded/pkg/compliance/crosswalk"
)

// The host baseline (ADR-098): the host-scoped evidence sources of the
// catalog, generated into compliance/baseline/baseline.yaml and shipped to
// hosts. The host agent evaluates the entries for its own hostname with the
// same collectors the central pull uses, so the two cannot disagree about
// what is checked, only about what they observe.

// ErrInvalidBaseline wraps every baseline rejection.
var ErrInvalidBaseline = errors.New("invalid host baseline")

const (
	baselineVersion  = 1
	maxBaselineBytes = 256 << 10
)

// Baseline is the parsed baseline file.
type Baseline struct {
	Version int                `yaml:"version"`
	Sources []crosswalk.Source `yaml:"sources"`
}

// isBaselineSource reports whether s is host configuration: a sysctl, an
// sshd setting or a probe marked Baseline, always naming its host.
func isBaselineSource(s crosswalk.Source) bool {
	switch s.Kind {
	case crosswalk.KindHostSysctl:
		m := sysctlRefRe.FindStringSubmatch(s.Ref)
		return m != nil && m[1] != ""
	case crosswalk.KindHostSSHD:
		m := sshdRefRe.FindStringSubmatch(s.Ref)
		if m == nil || m[1] == "" {
			return false
		}
		if m[3] != "=" {
			if _, err := strconv.Atoi(m[4]); err != nil {
				return false
			}
		}
		return true
	case crosswalk.KindHostProbe:
		m := probeRefRe.FindStringSubmatch(s.Ref)
		return m != nil && m[1] != "" && Probes[m[2]].Baseline
	}
	return false
}

// BaselineFromCatalog collects the catalog's host-configuration sources,
// deduplicated and sorted by key.
func BaselineFromCatalog(cat *crosswalk.Catalog) *Baseline {
	seen := map[string]bool{}
	b := &Baseline{Version: baselineVersion}
	for _, c := range cat.Controls {
		for _, s := range c.Evidence {
			if isBaselineSource(s.Source) && !seen[s.Key()] {
				seen[s.Key()] = true
				b.Sources = append(b.Sources, s.Source)
			}
		}
	}
	sort.Slice(b.Sources, func(i, j int) bool { return b.Sources[i].Key() < b.Sources[j].Key() })
	return b
}

// ForHost returns the sources that check host.
func (b *Baseline) ForHost(host string) []crosswalk.Source {
	var out []crosswalk.Source
	for _, s := range b.Sources {
		if hostOfRef(s.Ref) == host {
			out = append(out, s)
		}
	}
	return out
}

func hostOfRef(ref string) string {
	for i := 0; i < len(ref); i++ {
		if ref[i] == ':' {
			return ref[:i]
		}
	}
	return ""
}

// Marshal renders the baseline file, header included. Deterministic, so
// the repo copy can be compared byte for byte with a fresh generation.
func (b *Baseline) Marshal() []byte {
	var buf bytes.Buffer
	buf.WriteString("# Generated by `go run ./cmd/compliance-evidence baseline` from\n")
	buf.WriteString("# compliance/catalog/controls.yaml (ADR-098). Do not edit.\n")
	fmt.Fprintf(&buf, "version: %d\nsources:\n", b.Version)
	for _, s := range b.Sources {
		fmt.Fprintf(&buf, "  - {kind: %s, ref: %s}\n", s.Kind, strconv.Quote(s.Ref))
	}
	return buf.Bytes()
}

// ParseBaseline parses and validates a baseline file: strict YAML, the
// known version, host-configuration sources only, no duplicates.
func ParseBaseline(raw []byte) (*Baseline, error) {
	if len(raw) > maxBaselineBytes {
		return nil, fmt.Errorf("%w: larger than %d bytes", ErrInvalidBaseline, maxBaselineBytes)
	}
	var b Baseline
	dec := yaml.NewDecoder(bytes.NewReader(raw))
	dec.KnownFields(true)
	if err := dec.Decode(&b); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrInvalidBaseline, err)
	}
	if b.Version != baselineVersion {
		return nil, fmt.Errorf("%w: version %d, want %d", ErrInvalidBaseline, b.Version, baselineVersion)
	}
	seen := map[string]bool{}
	for _, s := range b.Sources {
		if !isBaselineSource(s) {
			return nil, fmt.Errorf("%w: %s is not a host-configuration source with a host", ErrInvalidBaseline, s.Key())
		}
		if seen[s.Key()] {
			return nil, fmt.Errorf("%w: %s listed twice", ErrInvalidBaseline, s.Key())
		}
		seen[s.Key()] = true
	}
	return &b, nil
}
