# Unheaded Kingdom — Prometheus Container
# Metrics collection and time-series database
# License: MIT, Copyright (c) 2024-2026 Steven Bellis

name: prometheus
description: "Unheaded Prometheus metrics container"
profiles:
  - default
  - unheaded-base
  - unheaded-observability
source:
  type: image
  protocol: simplestreams
  server: https://images.linuxcontainers.org
  alias: ubuntu/noble/amd64
config:
  boot.autostart: "true"
  boot.autostart.priority: "185"
  user.service: "prometheus"
  user.description: "Unheaded Prometheus metrics collection service"
devices: {}
