# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2024-2026 Stevie Bellis.

apiVersion: v1
kind: Service
metadata:
  name: haproxy-edge
  namespace: unheaded
spec:
  type: LoadBalancer
  ports:
    - { name: http,    port: 21080, targetPort: 21080 }
    - { name: https,   port: 21443, targetPort: 21443 }
    - { name: metrics, port: 21404, targetPort: 21404 }
